### ISSUE TITLE
Keyword generation occurring on pages that are saving

### ISSUE THREAD

**Issue by ghost** [spicywebau/craft-neo#112]
On pages that are saving in version 1.4.1 NeoFieldTypes are generating keywords hogging lots of memory and causing mass slowdown.
Looking at the change from 1.3.5 to 1.4.1 we noticed that the event here: https://github.com/benjamminf/craft-neo/blob/1.4.1/neo/fieldtypes/NeoFieldType.php#L43-L46
does not seem to be firing.
This causes Line 607 here: https://github.com/benjamminf/craft-neo/blob/1.4.1/neo/fieldtypes/NeoFieldType.php#L599-L618
to never occur.

This can be seen on all saves but causes massive delays or even memory exceptions on very long pages with a lot of NeoFieldType.

**Comment by ttempleton** [comment]
In my testing, those areas of the field type code are definitely running.  I'm not sure why the reporter of this issue was experiencing this issue, but at this stage I'm going to have to close this as not reproducible.  If anyone else is experiencing this and has more information, please let us know.
