### ISSUE TITLE
Hierarchy/order issues when adding new blocks. Possible issue from duplicate IDs in neoblockstructures table?

### ISSUE THREAD

**Issue by aaronbushnell** [spicywebau/craft-neo#128]
We're seeing a strange Neo issue on one particular Craft entry. I have two Neo fields in the entry:

| Field Name  | Field ID      |
|-------------|-----------|
| Modules |48 |
| Hero | 53|

When we add a new block to either of these Neo fields—in just this entry—and save it the Neo field blocks have a strange order and hierarchy. Here's a step-by-step of that experience when adding content to the **Modules** field:

#### 1. Current "Modules" field
![1](https://user-images.githubusercontent.com/315202/39250713-780460cc-486f-11e8-871d-4fe23f8ba0be.png)

#### 2. Add a new block to the bottom of the "Modules" field
![2](https://user-images.githubusercontent.com/315202/39250718-7b936c42-486f-11e8-889a-54ac322bddf3.png)

#### 3. Odd Neo hierarchy/order after saving with new block
![3](https://user-images.githubusercontent.com/315202/39250725-7f469b5c-486f-11e8-9115-5d54e0e6cfec.png)

### Database Records
I looked into this and noticed this entry+field combination has two records in the `neoblockstructures` table. Based on the other records here it appears as if there should only ever be one entry+field record. I wonder if this is the source of the problem. Here's a screenshot of the records I see for my entry:
![screen shot 2018-04-25 at 9 31 30 am](https://user-images.githubusercontent.com/315202/39248953-7ab1d8da-486b-11e8-871b-df90f3ccd7a0.png)

### Based on all this I have two questions:
1. **What's the best way to resolve this problem** in this particular entry? Is it to simply delete one of the duplicate records in the `neoblockstructures` table for each field ID? Or is there a better approach here?
2. **Do you know what may have caused this issue?** It doesn't seem to be a problem for any other entry so I'm not entirely sure why this would occur for this particular one. 

## Version information
- Craft 2.6.3011
- Neo 1.4.1

**Comment by theskyfloor** [comment]
Did you solve this? I am having this same issue and its a nightmare!!

**Comment by ttempleton** [comment]
I've no idea how the duplicated block structures would've happened, but that would definitely cause serious issues with a field's order and hierarchy.

@theskyfloor -- I'm not sure if or how @aaronbushnell might have resolved this situation, but if you or anyone else is experiencing this, I'd suggest that the older row in `neoblockstructures` should be deleted, and also any rows in Craft's `structures` and `structureelements` tables that are associated with the same `structureId` (make sure to take a database backup first, just in case).

The process of resaving a block structure for a given field/owner/locale combination actually involves deleting the old block structure and saving a new one, so for this issue to occur, it either would've somehow created an extra block structure at some point or it somehow failed to delete the old one.  Issue #156 was reported for Neo 2 a few months ago, which was similar in that it involved extra block structures somehow being created; we resolved that situation by looping for existing block structures and deleting them until we couldn't find one, *then* saving the new one.  There are some small differences in the block structure management in Neo 1 compared with Neo 2, but it's similar enough that we could investigate implementing a similar solution for Neo 1 that would hopefully fix this issue.

**Comment by ttempleton** [comment]
I've been playing around with a Craft 2 installation, temporarily removing the block structure deletion to deliberately generate multiple block structures for a field/owner/locale combination, and can confirm that I could cause the same behaviour as seen in @aaronbushnell's screenshot (in certain cases, I could also cause behaviour similar to issue #120 in that the old blocks would disappear).  I'm still not sure how this could've naturally happened; as I mentioned in my previous comment, Neo is set up to delete the old block structure when saving the new one, so only one block structure should ever exist for a field/owner/locale.

I've made an update to the block structure deletion code, to be included in Neo 1.5.1, which will repeatedly check for and delete block structures for a field/owner/locale until none are left.  With the update applied, if this issue has occurred on an entry that has versions enabled, you should revert the entry to the previous version and then it should be safe to add new blocks.  Otherwise, anyone experiencing the behaviour from the screenshot should be safe to just resave the entry or category after applying the update (though any new child blocks will end up at level 1, so they will need to be recreated in the correct place) and anyone experiencing the old block disappearance should *not* resave as that would cause the old blocks to be deleted; instead, delete the newly-added blocks and block structures from the database *before* applying the update.  In any case, make sure to take a database backup before updating Neo or performing any of these actions.

**Comment by aaronbushnell** [comment]
Wow, thanks so much for the detail here @ttempleton! Sorry—I'm late with a response here. I believe the way we resolved this was either:

1. Delete all the Neo fields in this entry and recreate them, or...
2. Delete the entire entry and recreate it

Really appreciate you taking such a deep dive into this one and all your hard work on this plugin, @ttempleton!

**Comment by ttempleton** [comment]
Thanks @aaronbushnell!

---

The block structure cleanup is included in Neo 1.5.1, which has just been released.  Due to the move to the `craft-2` branch since 1.5.0, this release won't appear on a Craft installation's updates page, so it'll need to be downloaded from its [release page on GitHub](https://github.com/spicywebau/craft-neo/releases/tag/1.5.1).

**Comment by aaronbushnell** [comment]
Thanks so much for your work on this! Appreciate it a bunch, @ttempleton
