### ISSUE TITLE
Admin login failure

### ISSUE THREAD

**Issue by ciaojames** [spicywebau/craft-neo#130]
We're getting this error when trying to login to Craft (2 not 3), which appears to be related to Neo: 

```
Internal Server Error
The table "{{neoblocktypes}}" for active record class "Craft\Neo_BlockTypeRecord" cannot be found in the database.
```

I can't get into the CMS to look at the issue from there - any suggestions of how I can bypass this error via FTP or a config file?

**Comment by ttempleton** [comment]
Sorry to hear that you experienced this and hopefully you got it sorted out.  It is strange that the block type table would be lost -- certainly Neo only drops it when uninstalling the plugin.  This sort of error can't really be bypassed, since, for example, recreating the table would lead to further errors, since any existing blocks would have nonexistent block types.  Unfortunately I don't think there would be any realistic solution to this type of situation other than to restore from a backup.
