### ISSUE TITLE
Craft 3 dev port: SQL error on entry delete

### ISSUE THREAD

**Issue by BryceBubbles** [spicywebau/craft-neo#135]
On deleting an entry with a fairly large Neo field, an SQL error is being thrown, with a stack trace that points to the Neo Field service. 

Error:
`PDOException: SQLSTATE[22003]: Numeric value out of range: 1690 BIGINT UNSIGNED value is out of range in '(`xxxxxxx`.`craft_structureelements`.`level` - 1)'`

The relevant stack trace lines from Fields.php:
Line 231: `$elementsService->deleteElement($deleteBlock);`
Line 362: `Neo::$plugin->fields->saveValue($this, $element, $isNew);`
Line 1839: `$field->afterElementSave($this, $isNew);`

I'm a bit new to reporting bugs, so hopefully this info is enough to help work out what's going on.

**Comment by BryceBubbles** [comment]
There were some blocks disabled, so I enabled them, saved the entry, then it could be deleted without error. I'm now trying to recreate the error.

**Comment by divyan** [comment]
I got the same problem. 
Workaround: If you delete them first from the deepest field and save the entry after each deletion it works. 
Directly deleting the highest field will give this error.

**Comment by vandres** [comment]
Same here. It happens when there are nested Blocks. Deleting the deepest Blocks first helps, but it no real solution for customers using it.

**Comment by ttempleton** [comment]
I've made a small change to how blocks are deleted, deleting them in reverse, which fixes the issue for me (the element deletion tries to adjust child elements' levels, but since we're operating on the original block data, deleting nested blocks in order may cause attempts to set a negative level).  @BryceBubbles @divyan and @vandres can you please confirm whether this has fixed the issue for you?

**Comment by ttempleton** [comment]
Thanks @vandres!

I will close this issue now but @BryceBubbles and @divyan please let us know if you continue to experience this error.
