### ISSUE TITLE
Craft 3 / Copy - Duplicate blocks

### ISSUE THREAD

**Issue by H-i-red** [spicywebau/craft-neo#140]
I see the duplicate button is replaced by a copy. Here comes a future request.. 😬
1. Be able to copy multiple selected blocks (Now I can only copy one at a time ?)
2. Bring back the duplicate button. For quick one copy use the duplicate button, for multiple, select your blocks and use the copy button. So you have two buttons one for copy & one for duplicate.

Perhaps rename `duplicate` to `clone`. (Shorter.. ; )
So we have `Copy`& `Clone` in the block menu dropdown.

**Comment by ttempleton** [comment]
Hi @H-i-red,

I do like the idea of restoring the duplicate/clone option as a quick alternative to copy/paste, so that option will return in the v2.1.0 release which we expect will be some time within the next month.

Regarding the ability to copy/paste multiple selected blocks, Ben discussed the complexities around this in issue #36 -- albeit using the duplicate option (this was before the copy/paste options existed) so the point about whether the blocks would duplicate in a chunk or under their respective original blocks is no longer an issue (with copy/paste we would just do the former).  I'd like to see this functionality in v2.1.0 and will see what we can do to make it happen.

**Comment by ttempleton** [comment]
The duplicate/clone option has now been restored to the dev-neo-2.1 branch.

I'll close this issue now, as issue #36 covers copying multiple selected blocks, so any updates regarding the implementation of that functionality will be posted there.
