### ISSUE TITLE
Neo 1.4.1 and Reasons support bug (flickering Reasons fieldtype layout)

### ISSUE THREAD

**Issue by SherriAlexander** [spicywebau/craft-neo#151]
With the latest versions of Neo for Craft 2 (v1.4.1) and the Reasons conditional plugin (v1.0.11), it's not possible to create new conditionals or edit existing ones in the Field Layout view if they're in a Neo field.  Selecting "Edit conditionals" triggers a wildly flashing Reasons modal, which does eventually stop flashing, but no changes that you make within the modal have any effect.

The author of Reasons is no longer updating their plugin, and though it seems that this change started happening with their latest release, they have stated that it is a Neo bug and they will not be fixing it (see https://github.com/mmikkel/Reasons-Craft/issues/40).

We have a large commercial site that's still in Craft 2, using both Neo and Reasons, and this is starting to be a problem for our client (we are adding new Neo fields, and are unable to create the same conditional field relationships we did before).  Updating to Craft 3 is not currently an option for us.

I know that Craft 3 development is your current focus, but would there be any possibility of fixing this issue in the Craft 2 release?  Thank you!

**Comment by ttempleton** [comment]
Hi @SherriAlexander,

Yes, we will fix this :+1: We plan to have a (probably) final release of Neo for Craft 2 sometime within the next month, which will include a fix for this issue.

**Comment by joshua-turner** [comment]
Hey @ttempleton - I'm still experiencing this issue after your fix.

Craft 2.7.0.

I have noticed that changes are applied, but only if you wait for the flashing to stop and after applying the conditions reopen the modal. It's a headache, but it's a workaround and thankfully isn't exposed to our end users.

Any help on this would be greatly appreciated - like @SherriAlexander, Craft 3 really isn't an option for us, since it would require rewriting several already-billed plugins.

**Comment by ttempleton** [comment]
Sorry about that, the flickering should be properly fixed now.

**Comment by joshua-turner** [comment]
@ttempleton Cannot thank you enough for this.

**Comment by ttempleton** [comment]
Neo 1.5.1 is out now and includes the fix for this issue.  Due to the move to the `craft-2` branch since 1.5.0, this release won't appear on a Craft installation's updates page, so it'll need to be downloaded from its [release page on GitHub](https://github.com/spicywebau/craft-neo/releases/tag/1.5.1).
