### ISSUE TITLE
Drag and Drop in or out of Neo blocks

### ISSUE THREAD

**Issue by vandres** [spicywebau/craft-neo#152]
Hi,

Would it be possible to implement a feature, that makes it possible to drag Neo blocks into child blocks? As an example: I made a structure for a "Grid", where the blocks are added in a "Grid-Column". Now the editor would like to move elements which where not in the "Grid" into it.

**Comment by ttempleton** [comment]
Hi @vandres,

Ben made some progress on implementing this for the Craft 2 version of Neo, and discussed his progress in issue #27 -- we can certainly port that work over to the Craft 3 version and ideally I'd like to see that completed and included in v2.1.0, but it'll require some rigorous testing to ensure it functions correctly with Craft 3 and that any of the weird bugs Ben mentioned are resolved.  If we reach a point where we're otherwise ready for v2.1.0 but we don't feel confident that this feature is ready, we'd need to hold this feature back a little longer; but this feature is definitely planned for inclusion in the Craft 3 version of Neo in the not-too-distant future.

**Comment by vandres** [comment]
@ttempleton Thank you for the information. If you need some testing, I can check the Beta for you

**Comment by ttempleton** [comment]
No worries @vandres and thanks for the offer to test the feature -- when we develop v2.1.0 it'll be available on a separate branch for anyone who wants to try it out and report any issues.
