### ISSUE TITLE
Error Message re-saving an entry that contains neo fields

### ISSUE THREAD

**Issue by seanconn** [spicywebau/craft-neo#159]
When I add neo fields to a section, it seems to cause an error when saving an entry for the second time. The entry saves correctly the first time, however if I open the entry and attempt to save it again (with or without changing any content) it generates the following error message:

Unknown Method – yii\base\UnknownMethodException
Calling unknown method: benf\neo\elements\db\BlockQuery::anyStatus()

Any Idea what this issue could be?

**Comment by ttempleton** [comment]
Hi @seanconn,

Can you please confirm the version of Craft CMS 3 you're using?  In version 3.0.17 the `anyStatus()` element query method was introduced for querying elements regardless of their status or whether they're enabled for a given site, with the intention that plugins could then override or extend that functionality where necessary.  Neo does not alter that functionality, but it does use `anyStatus()` to query for Neo blocks in some cases (and in fact needs to be updated in other places to take further advantage of it, in consistency with how Craft itself queries for elements of any status since 3.0.17).

As of Neo 2.0.3 (just released) Neo has been updated to require Craft CMS 3.0.17 or newer to prevent this issue from occurring in the future, but unless you're running a newer version of Craft and there's something else going on, updating Craft will fix this issue for you.

**Comment by seanconn** [comment]
I was on version 3.0.15. Updating seems to have solved the Issue, Thanks.
