### ISSUE TITLE
Live Preview Fails

### ISSUE THREAD

**Issue by 23d1** [spicywebau/craft-neo#160]
I know this has been fixed, but for some reason I'm still not able to use live preview in some installs. Here's a test environment example from the log;

`2018-11-22 15:00:48 [-][1][fbf3h52qpincln64is2d12c5b5][error][TypeError] TypeError: Argument 1 passed to benf\neo\elements\db\BlockQuery::setAllElements() must be of the type array, null given, called in /Users/a/Sites/test/craft/vendor/spicyweb/craft-neo/src/elements/Block.php on line 595 and defined in /Users/a/Sites/test/craft/vendor/spicyweb/craft-neo/src/elements/db/BlockQuery.php:320`

This is using Neo 2.0.3 on Craft 3.0.32

**Comment by ttempleton** [comment]
Thanks @23d1 -- we discovered that this was occurring when trying to access the children, descendants, etc. of a Neo block belonging to an entry that is associated via a relational field to the entry currently being edited.  Neo's live preview mode works by storing with each block an array of all blocks belonging to the same field, so queries for 'relative' blocks can query this set of blocks rather than querying the database, which therefore lets us show updated or new block data in the live preview.  In the case of elements from relational fields, the block array is not stored with each block (it doesn't seem to be possible to do this) but we were still trying to access the block data in the same way, which caused the error.

We've added a check to the block relative queries to confirm that the local block array has actually been set before trying to use it in live preview mode, which fixes this issue.
