### ISSUE TITLE
Multisite Problem: Getting unknown property

### ISSUE THREAD

**Issue by luke-nehemedia** [spicywebau/craft-neo#176]
Hello

I just set up a multisite and wanted to use NEO on this. However, every time I save the page, I get the following error message:

> Unknown Property – yii\base\UnknownPropertyException
> Getting unknown property: craft\elements\Entry::duplicateOf

The same happens when I try to edit the section properties, but only if it is set to "Single." The rest of the problems stays the same, also set to "structure" or "channel."

Any idea what causes this problem?
As soon as I remove the Neo-field from the field designer, everything works as expected.

**Comment by ttempleton** [comment]
Hi @luke-nehemedia,

I suspect that you're using Neo 2.1.4 with a version of Craft older than 3.0.31.  The fix for issue #171 in Neo 2.1.4 involved the usage of a `duplicateOf` Craft element property that was introduced in Craft 3.0.31.  When applying that fix and releasing Neo 2.1.4, I forgot to update Neo's minimum Craft version requirement; sorry about that.  Updating Craft to 3.0.31 or newer should resolve this issue.

If you are already using 3.0.31 or newer, though, can you please confirm the exact Craft and Neo versions you are using?

**Comment by luke-nehemedia** [comment]
Hello @ttempleton,

Thank you for the answer. The update did indeed fix the issue.
