### ISSUE TITLE
Blank tabs

### ISSUE THREAD

**Issue by timoteh** [spicywebau/craft-neo#182]
#### Description

We used to be able to create blank tabs inside a Neo field.
Now the empty tab gets deleted right after saving our Neo field. 

#32 

#### Steps to reproduce
1. Create a Neo field,
2. Add one block type,
3. Configure two tabs, one empty and one containing the field of your choice,
4. Save and realize the empty tab has disappeared

#### Other information
- Neo version: Neo 2.2.1
- Craft version: Craft CMS 3.1.5
- Is the affected Craft installation multi-site: No

**Comment by ttempleton** [comment]
Thanks for reporting, @timoteh.  Unfortunately, it looks like the changes in Craft's field layout code, as part of the project config update, might have made the type of workaround originally implemented by @benjamminf for #32 no longer possible.  It seems that workaround ensured that the empty tab was preserved by just making sure its fields were an empty array and not null, whereas now Craft actively ignores a tab if its fields array is empty.

We'll investigate to see if any other possible way exists to work around it, but otherwise, we could implement @benjamminf's idea of a lightswitch setting on block types to treat child blocks as a separate tab.

**Comment by ttempleton** [comment]
After investigating further, I've added some extra workaround where Neo checks if Craft's field layout `createFromConfig()` function stripped out any blank tabs, and puts them back in.  This update is included in Neo 2.2.2 which is out now.
