### ISSUE TITLE
Question About Future Dev

### ISSUE THREAD

**Issue by theskyfloor** [spicywebau/craft-neo#187]
#### Description

Just wondering if you might comment on Neo's future plans now that P&T is talking about adding nested Matrix to core in Craft 4. Will development continue until then? Will it continue after that? Thanks!

**Comment by vandres** [comment]
Hi @theskyfloor. Just curious, where did you read that?

**Comment by theskyfloor** [comment]
@vandres https://speakerdeck.com/brandonkelly/future-of-craft?slide=24 & https://speakerdeck.com/brandonkelly/future-of-craft?slide=25

**Comment by ttempleton** [comment]
Everyone at Spicy Web was definitely pleased and excited to hear about the features planned for Craft and particularly for Matrix fields in future versions of Craft, including nested Matrix fields.  At this stage, though, we feel that Neo would still offer enough in terms of features and convenience that it would continue to stand as its own field type in Craft 4.

Even if all of Neo's features were added to Craft 4 or another future Craft version, Neo development would still continue throughout the Craft 3 lifespan, and because Neo has the ability to convert its fields to Matrix (reintroduced in Neo 2.2.0), an update path does exist in that case (though the Neo fields' structural information would be lost).

**Comment by theskyfloor** [comment]
Thanks for the reply! I was guessing and hoping you would say that. I wanted to make sure this was out there so the community knows they can and should still rely on Neo's future development. Excited to keep using it myself!!
