### ISSUE TITLE
Craft 3 - disabled nested blocks still shown in Live Preview

### ISSUE THREAD

**Issue by rbaud** [spicywebau/craft-neo#213]
#### Description
Disabled nested blocks (any block not at the top level) in a Neo field are still shown in Live Preview, although they do not appear on the front-end once the page is saved. This seems to affect all levels of nesting (other than the top level).

#### Steps to reproduce
1. Slap together a fresh Craft 3 setup and install Neo from the Plugin Store.
2. Create a Neo field with a top-level block (e.g. **Top Level**) and a child block (**Child**), add it to the Homepage Section and insert something like the code below, adapted from the sample in the [craft-neo repo](https://github.com/spicywebau/craft-neo/blob/master/docs/templating.md), into `craft/templates/index.html`:
```
{% for block in entry.neoTest.level(1).all() %}
  <div>
    <h1>Top Level</h1>
    {% if block.children.all() is not empty %}
      {% for child in block.children.all() %}
        <h2>Child</h2>
      {% endfor %}
    {% endif %}
  </div>
{% endfor %}
```
3. Edit the Homepage in Craft with Live Preview open. Add a few **Child** blocks to one or more **Top Level** blocks, disable one or more children, see that they are still visible.

#### Other information
- Neo version: 2.2.8  & 2.3.3 (trial on my VM if it matters)
- Craft version: Craft Solo 3.1.20.1 & Craft Solo 3.1.25
- Is the affected Craft installation multi-site: No
- ~~(if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis:~~

**Comment by rbaud** [comment]
And as it goes, I just realized I've got a handful of Craft/Neo updates to apply. Could solve this. Will update and report back immediately. 🤦‍♂

**Comment by rbaud** [comment]
No dice. Fully upgraded, same issue. I've updated the **Other Information** portion of the original issue to reflect this.

**Comment by 23d1** [comment]
I can confirm this.

**Comment by Konsti-O** [comment]
#### Description
We still have a similar issue on different systems and projects. It works fine now for nested blocks with a depth of two levels. When you go deeper there is still a problem width the live preview. Because it would be a little confusing to describe all the cases i decided to make a short video:

[https://www.youtube.com/watch?v=DMis0CyZ7OE](https://www.youtube.com/watch?v=DMis0CyZ7OE)

What you see here is that everythings works fine when you only use two levels.
As soon as we get to the third level the content shows a very strange behaviour.

Here is how our template looks like reduced to the necessary code :

```
{% for block in entry.siteContent.level(1).all() %}
  {% switch block.type.handle %}
    {% case 'container' %}
      {% for column in block.children.all() %}
        {% for content in column.children.all() %}
          {% switch content.type.handle %}
            {% case 'mainHeadline' %}
          {% endswitch %}
        {% endfor %}
      {% endfor %}
  {% endswitch %}
{% endfor %}
```
In the Frontend everything works fine. Can someone confirm this? We spend some hours finding the problem in our template but nothing seems to work. 

#### Other information
- Neo version: 2.3.5
- Craft version: Craft Pro 3.1.30
- Is the affected Craft installation multi-site: No
