### ISSUE TITLE
Multi-site Content Being Overwritten

### ISSUE THREAD

**Issue by bryantAXS** [spicywebau/craft-neo#226]
#### Description
After migrating to 3.2, saving blocks in one language/site was overriding another.

#### Steps to reproduce
Context: we've got two sites, each of which has a different language (english/spanish)

1. Open a language in English, click save
2. Switch to spanish
3. Spanish site has English content.
4. Update content to spanish again, click Save.
5. Switch back to English, all things good. Resave.
6. Switch back to Spanish, has English content again.

#### Other information
- Neo version: 2.3.5
- Craft version: 3.2.1
- Is the affected Craft installation multi-site: Yes
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: It originally was not. Then, I made the update to Yes and the behavior seems to have corrected itself. However I am seeing weirdness when using Revisions and Drafts between languages.

**Comment by pvldigital** [comment]
Hi @bryantAXS,

Can you further explain the weirdness you're seeing with the revisions and drafts between languages?

**Comment by joao-proenca-ef** [comment]
Sounds like the same issue I'm having #225

**Comment by bryantAXS** [comment]
@pvldigital Bear with me because it's pretty confusing and I'm not quite sure what happened...

https://cl.ly/af25534a03fa

- This video shows an entry inside a Structure.
- Before updating to 3.2, this entry had English content and Spanish content, inside their respective sites.
- After updating to 3.2, I opened this entry and re-saved it.
- This video is me reopening the entry for a second time since the 3.2 update.
- In the video you'll see, English content is intact.
- After switching to Spanish site, English content overwrote the Spanish content on most areas, but when it switch to the Extra Rows tab, the relationship created were maintained as Spanish.

Here's the Propagation Method being used in this Structure: https://cl.ly/27744812c9ec

---

Also, I'm not sure if this is intended, but when using revisions, all the fields switch to basic text blocks: https://cl.ly/ee3d621ae7c9

**Comment by pvldigital** [comment]
Hi Everyone,

Small update. I'm currently making changes/fixes for Craft 3.2 and plan on releasing it in the next couple of days, stay tuned.

**Comment by bryantAXS** [comment]
Thanks @pvldigital, keep us posted!

**Comment by pvldigital** [comment]
Hi Everyone,

I've released a minor patch that should fix the multisite issues, in release 2.3.6. The minimum requirement will be >= 3.2.0.

**Comment by pvldigital** [comment]
Hi @bryantAXS ,

Sorry about the radio silence.

We've found the issue to be related to how the blocks were being saved in craft 3.2 for multisites. I've remade the block saving function so it's more inline with how the matrix field does it.

Release v2.4.0 should solve problems relating to how blocks are propagated to different sites which is what your issue is related to.

**Comment by riusi88** [comment]
Hi @pvldigital 

We are currently experiencing this issue, and we believe we've isolated it to the Neo fields we are using since they are the fields being effected. Multi-Lingual Neo Fields is a mission critical system we've built into the site, and this issue is unfortunately leading to lost work.

**Project Overview:**
The project has many language specific multi-sites, with Sections that have a propagation setting set to "Save entries to all sites enabled for this section", and a Neo block set to "Save blocks to all sites the owner element is saved in", with individual fields within the Neo block set to "Translate for each language".

It's worth noting that there are also many user groups, that only have permissions to edit one or two of the multi-sites. 

**The Issue:**
Our users report that sometimes their translations get propagated to other languages they don't have permissions for, and that they were not editing at the time of saving there changes. For example, a user editing in Spanish had their changes propagated to English. What's unfortunate is that when this happens, our users lose their progress in the language they were editing, and we have to roll back our entries to previously saved drafts or versions. 

I believe the core issue stems from the individual fields within the Neo blocks not respecting the "Translate for each language" feature, and somehow the fields contents are propagating to the wrong languages. 

**Info:**
Neo version: 2.7.11
Craft version: 3.4.20
Multi-Site: Yes, 10 multi-sites, each a separate language. 

Please let me know if you'd want a copy of the database, error logs, and composer.json.

**Comment by pvldigital** [comment]
Hi @riusi88,

We'll look into this. Will try to replicate the issue first before requesting for the db/logs/composer.

Can you also add a new issue with the information posted? Will make it easier for us to keep track. Thanks.

**Comment by riusi88** [comment]
Thank for looking into this @pvldigital . As requested I've created a new [issue #355 ](https://github.com/spicywebau/craft-neo/issues/355).
