### ISSUE TITLE
Neo `fieldLayouts` are removed from `project.yaml`

### ISSUE THREAD

**Issue by texasbaptists** [spicywebau/craft-neo#250]
#### Description

When running `./craft project-config/rebuild` Neo `fieldLayouts` are removed from `project.yaml.

#### Steps to reproduce
1. Build a Neo Field and set up the Field Layout tab on each block.
2. Compare changes in `project.yaml` with a previous version.
3. Run `./craft project-config/rebuild`.
2. Compare changes in `project.yaml` with version after building the Neo FIeld.

#### Other information
- Neo version: 2.4.4
- Craft version: 3.2.10
- Is the affected Craft installation multi-site: yes
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: no?
- (if multi-site, > 2.4.0) What is the propagation method of the neo field: save blocks to all the owner element is saved in.
- Is eager-loading used? no

![Screen Shot 2019-08-23 at 11 15 51 AM](https://user-images.githubusercontent.com/28350515/63607872-27358d80-c599-11e9-9840-d0d99fc5a37a.png)

**Comment by SwiseWeb** [comment]
I can confirm the same issue with the following setup: 

**Other information**
- Neo version: 2.4.7
- Craft version: 3.3.2
- Is the affected Craft installation multi-site: no
- Is eager-loading used? no

**Comment by punkch** [comment]
I am experiencing the issue while doing `craft project-sync/rebuild`. All the Neo fieldLayouts were removed from the project.yaml. The reason I've needed the rebuild, is because Neo was generating new uids for the fieldLayouts on change. 

#### Other information
- Neo version: 2.4.7 & 2.5.1
- Craft version: 3.3.4. & 3.3.5
- Is the affected Craft installation multi-site: no
- Is eager-loading used? no

**Comment by jmverges** [comment]
Same here
