### ISSUE TITLE
Nested Neo fields?

### ISSUE THREAD

**Issue by dangayle** [spicywebau/craft-neo#271]
I know it's probably not a good idea and I'm asking for trouble, but is there any way to do it?

**Comment by pvldigital** [comment]
Hi @dangayle,

I had a chat with one of the previous devs about the issue and basically Neo was only ever designed to work at the top level and was never meant to be nested. You can have a look at issue #101 and the original devs reply since it also applies here.

It's something we can look into for future versions of the plugin but currently have no plans for it.
