### ISSUE TITLE
Child blocks disappear on Preview -> Publish Changes

### ISSUE THREAD

**Issue by kellypacker** [spicywebau/craft-neo#305]
#### Description
Child blocks disappear on Preview -> Publish Changes.

#### Steps to reproduce
1. Add block, add child block
2. Click Preview (wait for checkmark) 
3. Close Preview
4. Click Publish Changes, child blocks disappear

#### Other information
- Neo version: 2.6.2
- Craft version: 3.4.3
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: No.
- (if multi-site, > 2.4.0) What is the propagation method of the neo field: Save blocks to all sites the owner element is saved in.
- Is eager-loading used? no

This seems related to https://github.com/spicywebau/craft-neo/issues/298, but it is not a loading issue. This happens with only one block on the page.

**Comment by pvldigital** [comment]
Hi @kellypacker,

So the child block would disappear but the top level block will still be in the entry, is that correct?

**Comment by kellypacker** [comment]
Hi @pvldigital, 
That is correct.

**Comment by pvldigital** [comment]
Can you send your composer.json + lock file to plugins@spicyweb.com.au? @kellypacker

**Comment by kellypacker** [comment]
@pvldigital done. Thanks for your help!

**Comment by javangriff** [comment]
@pvldigital I am encountering what seems to be the same issue with strange behaviour after making changes within live preview and then publishing changes. It is important to note that this issue only seems to affect nested blocks below 2 levels deep, at least for me.

Consider the following block structure before entering live preview:
```
- Parent Block
-- Child block level 1
--- Child block level 2 - Block 1
--- Child block level 2 - Block 2
```

If I then enter live preview and make any changes that trigger an update, close live preview and then publish the changes the block structure is updated to the following with `Block 2` now nested beneath `Block 1`:
```
- Parent Block
-- Child block level 1
--- Child block level 2 - Block 1
---- Child block level 2 - Block 2
```

How these blocks are displayed within the editor (after publishing) depends on whether or not blocks at `Child block level 2` can have child blocks added them as well. If they can the block structure will show as above, however, if not they will display at the correct level within the editor but no longer appear within the page content, presumably because they are in fact still children of `Block 1` within the system even though they do not display this way.

Hopefully, that makes sense.

**Comment by kellypacker** [comment]
An update on our specific issue: we narrowed it down to a conflict with the Scout plugin. We are still troubleshooting it to find the exact issue. 

For our case, the preview is removing all child blocks. But also on the initial save of an entry, all child blocks are missing. But it does save correctly on subsequent saves if the child blocks are added back in.

**Comment by rbaud** [comment]
We are continuing to face this, or a closely related issue -- possibly also related to [#323](https://github.com/spicywebau/craft-neo/issues/323), [#325](https://github.com/spicywebau/craft-neo/issues/325), [#356](https://github.com/spicywebau/craft-neo/issues/356) & [#364](https://github.com/spicywebau/craft-neo/issues/364) -- in Neo 2.7.15 and Craft 3.4.22.1.

This issue makes editing via Live Preview, a critical tool in our workflow and part of the appeal of Craft itself, unpredictable and therefore unusable.

### Here is what we have discovered:

1. This issue specifically affects changes made while using Live Preview. Making identical changes as described below OUTSIDE of Live Preview does not cause the issues we are describing.

2. This issue definitely affects Neo structures with 4 levels of nesting, but I have not exhaustively tested issues at lower/higher depths.

### Steps for reproducing:

1. Have a Neo structure with 4 levels of depth and at least two level-3 parents with at least one 4th/final level children each, like so:

- L1
--L2
---L3-A
----L4-X
---L3-B
----L4-Y

2. Open Live Preview and make ANY change that will cause the preview to refresh. Do this twice. This could be as simple as collapsing L1 and then expanding it again. It is not necessary for the changes to in any way affect the structure/content of the Neo field or affected blocks.

The first Live Preview refresh/reload/update will be fine. For us, the second throws an "Unable to find one of the following templates" error (this is because our Neo uses different templates at different levels), which is an indication that the nesting/structure has changed.

3. Close Live Preview, make note that as yet the nesting/structure in the control panel has not changed, and then _Publish changes_.

4. After the control panel has refreshed, you should notice that the structure is now broken like so:

- L1
--L2
---L3-A
----L4-X
**----L3-B**
**----L4-Y**

**Comment by ttempleton** [comment]
Going to close this issue now, due to its age and inactivity.  If the issue persists with the latest versions of Neo and Scout, please let us know and we'll reopen.
