### ISSUE TITLE
Empty fields makes multiple queries and duplicated queries

### ISSUE THREAD

**Issue by mmorkt** [spicywebau/craft-neo#327]
#### Description

Got a problem with empty fields generating multiple queries and duplicated queries in Neo.
A template example:

```
{% set neo = entry.neo.level(1).all() %} 
{% for index, block in neo %}
  {% set spaceBefore = block.spaceBefore %}
  {% set blockType = block.type.handle %}

  {% switch blockType %}
    {% case 'example' %}

    {% set attributesBlock = {
        class: [
            spaceBefore,
        ]
    } %}
```

```
dropdown / select:
 › Option = 'value one'
 › Option two = 'value two'
 › Option three = 'value three'
 › Option four = ''      ‹ default
```

#### Steps to reproduce
1. Include dropdown or color field without a value set to default
2. fetch it  
3. look at the number of queries / duplicated queries
4. Now add a value and test it. The queries are reduced 

#### Other information
- Neo version: 2.7.3
- Craft version: 3.4.11
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: No
- (if multi-site, > 2.4.0) What is the propagation method of the neo field: 
- Is eager-loading used? No

**Comment by pvldigital** [comment]
Hi @mmorkt, 

Hmm that is strange. I'll have a look into it.

**Comment by ttempleton** [comment]
Testing this with the latest versions of Neo and Craft, the number of queries seems consistent regardless of the field value, so I'm going to close this issue due to its age and no other reports of this issue.  If you're still experiencing this behaviour with the latest versions of Neo and Craft, please let us know and we'll reopen the issue.
