### ISSUE TITLE
Multi language site: blocks don't propagate to other languages

### ISSUE THREAD

**Issue by janmeeus** [spicywebau/craft-neo#328]
#### Description
Multi (language) site setup: NL and EN
Trying to add Neo blocks to a homepage (entry type "Single"). The blocks don't get propagated from NL to EN.

#### Steps to reproduce
1: Neo block gets saved in NL. It doesn't propagate to EN. 
2: Adding the Neo block in EN; the previous Neo block in NL gets removed.

#### Other information
- Neo version: 2.7.4
- Craft version: 3.4.12
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: No
- (if multi-site, > 2.4.0) What is the propagation method of the neo field: Save blocks to all sites the owner element is saved in
- Is eager-loading used? No

**Comment by pvldigital** [comment]
Hi @janmeeus,

Is this issue only occurring for entry type "Single"? Or are "Structure" and "Channels" types affected as well?

**Comment by pvldigital** [comment]
@janmeeus,

I've made a fix for the issue. Will be releasing it later this afternoon (my time).

**Comment by janmeeus** [comment]
> Hi @janmeeus,
> 
> Is this issue only occurring for entry type "Single"? Or are "Structure" and "Channels" types affected as well?

@pvldigital To answer this question: I tested it with a Structure and there it was propagating fine. So only on a Single.

**Comment by janmeeus** [comment]
Looks like your fix did the trick. Thank you!

**Comment by taylordaughtry** [comment]
@pvldigital  Hey! Sorry to bump this, just a super-quick followup question—after updating to get this fix, is there a way to trigger Neo to propagate its content for all entries? I have a situation in a client project where we've created a new Site, and the entries have already propagated with version `2.7.20` in place.

Of course, manually making a change in the source Site + saving propagates it properly, but I'm hoping there's a bulk way to do this, since we've already created the new Site + propagated all the entries.
