### ISSUE TITLE
[question] How to test for broken neo structures after update to 2.7.x?

### ISSUE THREAD

**Issue by tomdavies** [spicywebau/craft-neo#336]
#### Description

In the release notes for [2.7.0](https://github.com/spicywebau/craft-neo/releases/tag/2.7.0) it says:

> This update contains a schema update which could potentially break the structure of the neo blocks. Make sure to backup your database and do the update locally first as it includes migration of all neo blocks. If the structure is indeed broken, re-saving the page should resolve it.

Can you tell me how this issue presents to the user when it occurs? i.e. how do we test after running the update + migration in order to know if we are affected?

My question is aimed at avoiding the issue in #317, but we're using Neo on a pretty large production site, so manually testing every entry isn't feasible. 

Would running a resave on all entries just in case potentially be the safest thing to do?

Cheers for your help

#### Other information
- Neo version: 2.7.0 / 2.7.7.1
- Craft version:

**Comment by pvldigital** [comment]
Hi @tomdavies,

Ah I should've gave a better explanation. That warning was mostly because blocks that might appear after updating. Once you remove those blocks and save it should fix itself. It should be fine when updating to the latest neo version, most issues with the migration was taken care of.

I suggest cloning the site locally, update and then see if anything is out of place first.

**Comment by phillmorgan28** [comment]
Hi

I am also affected by this issue. I have run an updated test on our site and it appears that the majority of our data is being lost.  Re-saving entries either through CLI or control panel does not correct the issue.

For example, our header/nav uses Neo on a global. Upon update, all but one of the menu items were lost. When re-saving repeatedly through the control panel, 4 out of 8 items were recovered one at a time. The rest appear to have been deleted.

2.7.0 is certainly a breaking update which will most likely require the majority of users to re-create entries rather than simply re-save.

Craft Version: 3.4.16
Neo Version: 2.7.0

**Comment by tomdavies** [comment]
Gotta say this is giving me the fear about updating, as we're using on a site with 3000+ entries that use Neo, so checking each one is infeasible. But this also seems different from the description in the release notes / @pvldigital's last post: that was about unwanted blocks appearing, not existing blocks being lost. 

Is this actually new bug report @phillmorgan28?

**Comment by pvldigital** [comment]
@phillmorgan28 @tomdavies stay at version `v2.6.x` for now. I'll have a look further into the issue and the migration file. `v2.6.x` should be fine since `v2.7.x` mostly changes how the structure is built.

**Comment by pvldigital** [comment]
@phillmorgan28 are you using a multi-site setup?

**Comment by pvldigital** [comment]
@tomdavies @phillmorgan28 with my latest commit and testing, I can see no issues with updating from

Craft 3.3.10 -> 3.4.16
Neo 2.5.10 -> latest commit

All the globals, category and entries that has neo blocks are correctly set for me.

I'll do some further testing with multisite and bigger sites with a huge amount of entries.

**Comment by tomdavies** [comment]
@pvldigital we are using multi site FWIW. I am also going to do some testing too, as I figure I can fairly easily write a debug template that counts the neo blocks displayed on each entry, and can use that to before/after test

**Comment by pvldigital** [comment]
@tomdavies thanks for the info.

You can test the latest commit by changing the version within composer to `dev-craft-3-dev`, this should switch to the dev branch of the repo.

**Comment by pvldigital** [comment]
@tomdavies I've been testing with the latest releases and it seems to be working correctly for me (updated some sites to the latest). I think the issue lied with #326 + some issues with the migration file which is now updated. The only thing the migration should do is add the `sortOrder` value to the blocks, which after updating will be used instead.

**Comment by tomdavies** [comment]
Thanks for following up @pvldigital. Back on this project next week so will take a look then
