### ISSUE TITLE
Missing Element Thumbnails when switching to a "hidden" tab

### ISSUE THREAD

**Issue by loweoj** [spicywebau/craft-neo#360]
#### Description
1) Asset field "element thumbnails" are not displaying on "hidden" tabs when switching between field tabs.
2) Asset selector button is incorrectly positioned when asset selector is last field in the tab - notice missing lower border of the button here -https://www.dropbox.com/s/d9f807wme1422im/Screenshot%202020-06-05%2015.34.13.png?dl=0

#### Steps to reproduce
1. Create a Neo field with two tabs. Add an asset field to the second (initially hidden) tab.
2. Upload an asset to hidden tab. Save.
3. Refresh the page, switch to tab 2, notice that the element thumb hasn't loaded.

#### Other information
- Neo version:  2.7.15
- Craft version:  3.4.22.1
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: N/A
- (if multi-site, > 2.4.0) What is the propagation method of the neo field: N/A
- Is eager-loading used? N/A

**Comment by ttempleton** [comment]
Thanks for reporting this, the asset thumbnails will be fixed in the next release.

Regarding the asset field selector and the missing border -- this is happening due to empty asset fields having a little less height on them compared with other empty element fields, which causes the selector button for asset fields to overflow the field area.  This seems to be happening regardless of context.  In particular, it's also pretty noticeable when an asset field is the last field on a Matrix block; even if Matrix blocks don't hide the overflow like Neo blocks do, an asset field's selector button will be noticeably closer to the block border than entries/categories/etc.  So the ideal solution to fix asset field borders being cut off when they're the last fields in Neo blocks would be for the underlying style bug in Craft to be resolved.

**Comment by ttempleton** [comment]
Neo 2.8.11 has just been released with the fix for this issue.
