### ISSUE TITLE
Nested blocks appear out of root/parent block

### ISSUE THREAD

**Issue by markjoeljimenez** [spicywebau/craft-neo#364]
#### Description
All nested blocks have some how moved out of parent scope and appear top-level.

![Screen Shot 2020-06-11 at 5 28 31 PM](https://user-images.githubusercontent.com/5943430/84441309-91432000-ac09-11ea-898f-ac3cfe51878c.png)

We have our Neo blocks set up like this:

- Panel
    - Row
        - Column
            - Custom block

![Screen Shot 2020-06-11 at 5 28 45 PM](https://user-images.githubusercontent.com/5943430/84441437-cf404400-ac09-11ea-96a3-4288c018846e.png)

We're using headless CraftCMS in a JAM stack so the order and content of these panels are vital. Since the nested blocks popped out of the root block, it caused a mapping of an undefined variable error and ultimately a 503 error on the backend.

We're not quite sure what happened but we assume this happened on save entry?

#### Steps to reproduce
1. On save entry?

#### Other information
- Neo version: 2.7
- Craft version: 3.4.19.1
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: Yes
- (if multi-site, > 2.4.0) What is the propagation method of the neo field: "Save blocks to all sites the owner element is saved in"
- Is eager-loading used? No

**Comment by markjoeljimenez** [comment]
Nevermind! Looks like this version [2.7.14](https://github.com/spicywebau/craft-neo/releases/tag/2.7.14) fixes my issue.

I'll keep this issue open for now and will close if it does!

**Comment by MK-PL** [comment]
Nested blocks move out of root/parent block to the top level also in revisions. When you revert previous version the blocks arrangement will be broken and you will have to recreate all arrangement on your own (because all versions are broken, even last one). In a normal page edition, the arrangement is fine.

Screenshot with page edit:
![obraz](https://user-images.githubusercontent.com/8502239/85024659-ae7e6e00-b176-11ea-9a33-0a979826d903.png)

And screenshot with page revision:
![obraz](https://user-images.githubusercontent.com/8502239/85024745-cce46980-b176-11ea-8d7a-dc28c4c4792e.png)

**Steps to reproduce**

    Save entry and check revisions

**Other information**

- Neo version: 2.7.18
- Craft version: 3.4.24
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: Yes
- (if multi-site, > 2.4.0) What is the propagation method of the neo field: "Save blocks to all sites the owner element is saved in"
- Is eager-loading used? No

**Comment by markjoeljimenez** [comment]
@MK-PL, would you like to create a new ticket? I'm going to close this one as 2.7.14 does technically solve my issue.
