### ISSUE TITLE
Integrity Constraint Violation on rebuild / apply

### ISSUE THREAD

**Issue by BrandonJamesBorders** [spicywebau/craft-neo#405]
#### Description
Have parallel development happening on a site. Each branch is adding/modifying blocks. When merging branches and applying the changes we get the following error:
```
Applying changes from your project config files ... error: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'fieldId' cannot be null
The SQL being executed was: INSERT INTO `neoblocktypes` (`fieldId`, `name`, `handle`, `sortOrder`, `maxBlocks`, `maxSiblingBlocks`, `maxChildBlocks`, `childBlocks`, `topLevel`, `uid`, `fieldLayoutId`, `dateCreated`, `dateUpdated`) VALUES (NULL, 'Link', 'link', 1, 0, 0, 0, '', 1, '9eac68b8-60f5-4ee2-9acc-e8f7178f0bc1', 131, '2020-10-14 19:24:02', '2020-10-14 19:24:02')
``` 

#### Steps to reproduce
1. In attached file, init craft project with files and db from`branchA`'
2. Merge content from `branchB`
3. Run config apply. 
4. Get error message

#### Other information
- Neo version: 2.8.11
- Craft version: 3.5.12.1
- (if multi-site) What is the affected Neo field's propagation method: No
- Is eager-loading used? No

[toNeo.zip](https://github.com/spicywebau/craft-neo/files/5380586/toNeo.zip)

**Comment by ttempleton** [comment]
Hi @BrandonJamesBorders,

Thanks for providing the files.  According to the YAML file for the affected Neo block type, it belongs to a field with a UID that doesn't exist for any field anywhere within the DB, or the field YAML files.  I don't think it's a case of the Neo field being deleted without deleting its block types, because that field UID still appears in one field layout.  It seems more like the Neo field's file is missing.  Double-check to make sure the relevant field file hasn't just failed to be written by Craft at some point for some reason, but Craft is in control of updating fields in the project config, strictly speaking -- Neo itself only controls updating block types and block type groups after the rest of the field's settings are updated by Craft.
