### ISSUE TITLE
Block grouping (the dropdown) not shown when there is only one block in the group

### ISSUE THREAD

**Issue by proimage** [spicywebau/craft-neo#414]
#### Description
If there's a group of blocks with only one block, then instead of having a dropdown with a single option, the grouping is hidden entirely, and that single block is shown instead.

This also happens when there is only one valid block in a group of multiple blocks for the current context.

For example, I have a group called "Containers", with two blocks, "Container" and "Tabbed Container". "Container" blocks are not allowed to be nested inside other "Container" blocks (because reasons), but "Tabbed Container" blocks are.

When in the context of an existing "Container" block, adding a nested "Container" block isn't allowed, so the only valid block in the "Containers" group is the "Tabbed Container" block. Instead of showing the "Containers" group as a button with a dropdown, the "Tabbed Container" block is shown at the top level:

![image](https://user-images.githubusercontent.com/1027523/98839309-0e3f2380-244e-11eb-98f0-f17f9418bf82.png)

My suggestion would be to add a simple lightswitch toggle on the Group panel, to determine if that group should collapse when it only has a single block or not:

![image](https://user-images.githubusercontent.com/1027523/98840005-f61bd400-244e-11eb-8a1c-c97b5eb1d62c.png)

#### Steps to reproduce
1. Create a Neo field with a couple of blocks.
2. Put a single block inside a group.
3. The group will not be shown; the block will be shown instead.

#### Other information
- Neo version: 2.8.12
- Craft version: 3.5.14

**Comment by ttempleton** [comment]
Yeah, this is how groups with one block type have been displayed since the early days of Neo (see #5).  It's an interesting question about whether it should display a dropdown anyway, or at least have the option, as you suggest.  My personal preference is the current behaviour; my concern is that, when you only have one block type in a group, displaying the dropdown doesn't help much in terms of block type organisation and space-saving, and it's arguably less efficient in that it introduces an extra click to create those blocks.  That said, I'm open to the argument that consistency in block type group presentation is important too (especially in a case like your containers example), it wouldn't be hard to add the option and those who don't want it could just choose not to use it.  I'll need to have more of a think about it.

**Comment by proimage** [comment]
While I'm all for reducing clicks where possible, I think that goal is overshadowed by the mental confusion caused by unexpected behavior. 

Let's consider the two instances where a group could only have a single block.

1. A group was created, given a name, and manually assigned by the developer to have only a single block. The intended result of the developer would be that the block appear in that group's dropdown. If they just wanted a "top-level" block button, either no group, or an unnamed group, would have sufficed.
2. Due to the context in which the buttons are being shown (like my original example), all other possible blocks are invalid and only one block can be used from the group. In this case, the _content author_ has already come to expect (using my example) the "Containers" group dropdown button. Replacing that dropdown button with one of its children is unexpected behavior that would likely cause confusion.

In either case, replacing the dropdown leads to results which are unexpected by either the dev or the content author. I would go so far as to say that adding the option but leaving the current behavior as default is insufficient, and that the current behavior should have to be intentionally selected by the dev.

But that's just me... ¯\\\_(ツ)_/¯

**Comment by ttempleton** [comment]
Just released Neo 3.0.0-RC2 which adds a plugin setting for globally setting the default behaviour for this (`defaultAlwaysShowGroupDropdowns`, defaults to `true`), and also adds the ability to control the behaviour on a per-group basis. The group setting is implemented as a dropdown, rather than a lightswitch, to allow the ability to fall back to the default setting.

![screenshot1](https://user-images.githubusercontent.com/19421878/165736181-92b78b27-7217-4f31-b529-90de57b78c57.png)

<img width="113" alt="screenshot2" src="https://user-images.githubusercontent.com/19421878/165736226-c6694e7c-98cd-47b0-a26e-850e4ccf1c92.png">
