### ISSUE TITLE
Updating to 2.10

### ISSUE THREAD

**Issue by JordanMed** [spicywebau/craft-neo#467]
#### Description
I see in the change log is says "Neo now requires Craft 3.6.6 or later" but I can only update craft to 3.6.17 is this a typo? 

#### Steps to reproduce
1.
2.
3.

#### Other information
- Neo version:
- Craft version:
- (if multi-site) What is the affected Neo field's propagation method:
- Is eager-loading used?

**Comment by ttempleton** [comment]
No, that's correct, Neo's Craft version requirement is now [`^3.6.6`](https://github.com/spicywebau/craft-neo/blob/2.10.0/composer.json#L28).  If you specifically need Craft 3.6.6 instead of the latest version for any reason, and none of your other plugins or modules require newer versions than 3.6.6, you would be able to enforce 3.6.6 by changing your existing requirement for the `craftcms/cms` package in your project's `composer.json` file to `"craftcms/cms": "3.6.6"`, then running `composer update`, and Neo's requirements will allow that to happen.
