### ISSUE TITLE
Hi, does neo transfer data outside of the EU / EEA? What data is bring processed, we are HQ'd in Ireland.

### ISSUE THREAD

**Issue by companjon** [spicywebau/craft-neo#471]
#### Steps to reproduce
1.
2.
3.

#### Other information
- Neo version:
- Craft version:
- (if multi-site) What is the affected Neo field's propagation method:
- Is eager-loading used?

**Comment by ttempleton** [comment]
Neo stores the following data within a Craft installation:

- the block types and block type groups belonging to any Neo fields you've created;
- the blocks belonging to any Neo field for each entry/category/etc. where the field is used;
- the block structures, i.e. which blocks are child blocks of which other blocks and at which nesting level do they exist;
- the content you've entered for the Neo blocks, which are stored in the same format as any Craft entry/category/etc.

This data is stored within the same database as your Craft installation.  The cases in which Neo data would be transferred from your web server in some form are:

- to a user of the Craft control panel, for the purpose of creating and editing Neo fields and Neo field contents;
- to a user of your website, where you have chosen what Neo-related data to publicly share on your website.

However, since you are the one entering the Neo block/field data for your Craft installation, you have full control in terms of avoiding entering content that could potentially violate the GDPR.

Hopefully that answers your question, but if you have any further questions, feel free to let us know.
