### ISSUE TITLE
Disable blocks based on site/language?

### ISSUE THREAD

**Issue by JacquesFernandes** [spicywebau/craft-neo#476]
#### Description
Question:
Is it possible to disable Neo blocks based on the "site" or "language" (in a multisite setup)? 
The aim is to disable a specific block on one site, but have it enabled on the others.

Would I just update the propagation method?

#### Steps to reproduce
None

#### Other information
- Neo version: 2.9.2
- Craft version: 3.6.10
- (if multi-site) What is the affected Neo field's propagation method: "Save blocks to all sites the owner element ...."
- Is eager-loading used? Nope

**Comment by ttempleton** [comment]
Yeah, that's correct; since the enabled / disabled state is stored on a per-block basis, you would need to change the propagation method for the field, to make them separate blocks for each site / site group / language, before the newly-separated blocks could have different enabled / disabled states.
