### ISSUE TITLE
Duplicate blocks appearing with identical IDs when eager-loaded 

### ISSUE THREAD

**Issue by Ticolyle** [spicywebau/craft-neo#487]
#### Description
This site has experienced this bug before (last year) but we haven't had any problems recently until I applied updates today. After updating to Craft 3.7.6 and Neo 2.11.3 an eager loaded NEO block on my site is returning duplicates of itself. Within the CMS only one block can be seen (field is limited to one top level block), but on the template they are duplicated with identical `id`. 

Extremely similar to the previously reported #387. sjcallender suggests in the comments there to delete the block and re-create. I attempted a 'copy' > 'delete' > 'new' > 'paste' on the offending block. This resolved the issue on the entry I tried it, however we have over 100 entries using this field and I am reticent to manually go and update each of these entries if avoidable. 

#### Steps to reproduce
1. Upgraded craft CMS to 3.7.6 and Neo to 2.11.3
2. View an entry template using my eager loaded block
3. See the block output multiple times

#### Other information
- Neo version: 2.11.3
- Craft version: 3.7.6
- (if multi-site) What is the affected Neo field's propagation method: n/a
- Is eager-loading used? Yes

**Comment by ttempleton** [comment]
I'm unable to reproduce this, but then in #387 I was only able to reproduce it for one entry. If possible, could you please send your composer.json/lock and database backup to plugins@spicyweb.com.au and we'll have a look at it.

**Comment by ttempleton** [comment]
Should now be resolved in Neo 2.11.6, the plugin will run a migration to remove the old block structure data that's causing the blocks to appear twice.

**Comment by Ticolyle** [comment]
@ttempleton Thank you so much for digging into this bug and issuing an fix so quickly! I will attempt this update locally soon.

**Comment by nickdunn** [comment]
@ttempleton thanks for fixing this one. 

I've noticed the release note says:

> This release includes a migration to delete old Neo block structure data on single-site Craft installs that could cause duplicate blocks to appear when eager loading or using GraphQL. If your Craft install is single-site, make sure to backup your database before updating Neo.

The reference to doing a backup suggests that maybe this upgrade could break something unexpectedly? Do you know why the duplicates weren't purged in the first place, and is there any chance this update could delete something it's not supposed to?

**Comment by ttempleton** [comment]
@nickdunn On single site Craft installs, Neo block structures were originally saved with a `null` owner site ID, but at some point (I *think* Neo 2.4) this was changed to instead save the site ID from the existing site. When a Neo field's contents are saved, Neo 'updates' the block structure by deleting the old one and creating a new one. Due to the change in saving the owner site ID and how the deletion of the old block structures works, after that change was made, the block structures with `null` owner site ID wouldn't be deleted when saving the Neo field's contents. This wasn't really a problem when not using eager-loading, since Neo block queries would automatically add the structure ID to the query when the query only applied to one field/owner/site combination. But when eager-loading, the two block structures would cause duplicate blocks to appear.

The migration added in Neo 2.11.6 tries to find any block structures with `null` owner site ID, where there also exists a block structure for the same field and owner element, but with a non-`null` owner site ID. It then deletes the `null` ones (which is safe to do since they will be older). Finally, if there are any block structures left with `null` owner site ID, they're updated to store the existing site's ID so they won't cause any duplicate blocks to appear when eager-loading in the future.

You definitely shouldn't have anything break with this update, but I still felt like it was the right thing to include the warning there, just in case there were any unforeseen problems with the migration deleting any block structures it wasn't supposed to. We haven't had any reports of that, though, and I don't expect to have any at this point.

**Comment by nickdunn** [comment]
Thank you for the explanation — really helpful.
