### ISSUE TITLE
Entry with Neo field in section causing entries to take a long time to save

### ISSUE THREAD

**Issue by zizther** [spicywebau/craft-neo#496]
#### Description
I have a section which contains a Neo field which contains 3 blocks, these blocks contain a number of fields including matrix, assets, redactor, plain text, dropdowns, lightswitches and Typed link field (version 2.0.0-rc.1).
Entries can have between 20-30 blocks, as well as other field content in the entry, these include asset, plain text, dropdowns, lightswitches and SEOmatic fields.

The entry takes about 5 seconds to load, however when saving the entry it can take between 10-15 seconds.

There were some performance issues with SEOmatic, which I've gone over with Andrew on, we have tested some optimisations coming in SEOmatic 3.4.5, these have improved the load and save time, but the remaining large chunk of time seems to be with Neo, I believe this to be the case as I have tested entries with SEOmatic, asset and redactor fields, these load and save very quickly. The only difference is the Neo field itself.

Another issue I have noticed, which maybe related; it takes 25 seconds to load and save a category, in the Categories section in the CP, which has an entries field pulling in related entries from the section containing the Neo field.
I have looked at the Yii debug logger, it shows there are 31,233 events and 3,861 DB calls, which seems ridiculous for loading relations.

I am not sure if this issue is due to how Craft pulls in relations (loading in all the Neo data), or maybe something new in 3.7 with the slide outs?
I wanted to touch base with you on this part of the issue first, incase there are some optimisations which could happen your end, but if you think this may be an optimisation for Craft, I can add an issue there.

Happy to help look into the issue and supply you with anything you need.

#### Other information
- Neo version: 2.11.8
- Craft version: 3.7.10

**Comment by thomasjwalsh** [comment]
I'm experiencing something similar. I have a page with a lot of blocks 24 parent blocks and about 20 child blocks (with asset fields and text fields). I'm getting 3358 db queries on save (~7000ms per save on the front end). I was originally using super table but restructured to use neo. With super table I didn't notice a big saving lag.

- Neo 2.11.8
- Craft  3.7.10 (pro)

**Comment by ttempleton** [comment]
Here’s what I've found in my testing:

- Resaving a Neo field with 26 blocks, with only one change to one subfield, ran 3642 queries, and the subsequent running of queue jobs ran 2313 queries.
- Resaving a Matrix field with 26 blocks, with only one change to one subfield, ran 2011 queries, and the subsequent running of queue jobs ran 1567 queries.
- Resaving a Super Table field with 26 rows, with only one change to one subfield, ran 1904 queries, and the subsequent running of queue jobs ran 2291 queries.
- Resaving an entry with no block element fields, only one change to one plain text field, ran 152 queries, and the subsequent running of queue jobs ran 136 queries.

While the numbers for Neo are higher than the other two block element field types, it's worth noting that, if extra field resaving is happening, Neo will naturally have more work to do as it will need to resave block structure data, something Matrix and Super Table don't have to worry about.

Given the results with Matrix and Super Table still seem pretty high, I'm inclined to believe this is being caused by Craft. I'm honestly not sure if it's a bug or if those numbers should be expected (since, for instance, the new entry revision needs to be created), but at this stage I don't believe it's a Neo bug. If it is a Craft bug and it gets fixed (or otherwise if optimisations can be made on Craft's end) and Neo's query count doesn't reduce with that, then we'll be happy to reopen the issue.

**Comment by ttempleton** [comment]
I overlooked the comment regarding the event count, so I retested the above cases so I could share the numbers I got:
- Neo: 10693 events
- Matrix: 12623 events
- Super Table: 6326 events

Neo's event count was similar to Matrix's, and while Super Table's event count was lower, it’s worth noting that Super Table hasn't yet been integrated with the canonical element merging system in Craft 3.7, so I'm guessing that would explain the lower numbers in Super Table's case.

(Also this is probably a duplicate of #494, so will encourage any further comments to be posted there.)

**Comment by turnstylerj** [comment]
@ttempleton Looks like there's a fix available coming in 3.7.11, would be great to get this implemented into Neo: https://github.com/craftcms/cms/issues/9802#issuecomment-914910382

**Comment by ttempleton** [comment]
Just made those changes in Neo, will need to hold off on a release until the next Craft release, but in the meantime you can change your Neo requirement in your composer.json to `2.11.x-dev`.

**Comment by brandonkelly** [comment]
Thanks for being on top of that, @ttempleton! Craft 3.7.12 is out now.

**Comment by ttempleton** [comment]
Thanks @brandonkelly :+1:

Just released Neo 2.11.10.
