### ISSUE TITLE
Entries are edited when expanding or collapsing a neo block

### ISSUE THREAD

**Issue by jimyhse** [spicywebau/craft-neo#517]
#### Description
When we're expanding or collapsing a neo block, the entrys state is changed to edited. This despite the fact that we have not edited any property. This can confuse one into believing that a page has changed, even though it is not.

#### Steps to reproduce
1. Open an entry with a neo block. Ensure that the entry doesn't have any unsaved changes (i.e. the revision dropdown says "Current").
2. Double click on a neo block header to toggle the exansion of the block or select Collapse/Expand in the action menu of the block. Notice how the entry is reloaded and there are unsaved changed (i.e. the revision dropdown has changed to "Current - Edited").

#### Other information
- Neo version: 2.11.17
- Craft version: 3.7.20
- (if multi-site) What is the affected Neo field's propagation method: -
- Is eager-loading used? No

**Comment by ttempleton** [comment]
Thanks for reporting this. It was happening because blocks' collapsed states were being stored in the entry form data, which was intentional, but not really necessary since the block's new collapsed state is saved in Craft's data cache as soon as it's changed anyway. Since keeping it in the entry form data was causing issues with provisional drafts in Craft 3.7, I've gone ahead and removed it in Neo 2.11.18, which has just been released.
