### ISSUE TITLE
[Q] What does "Applying new propagation method to Neo blocks" do?

### ISSUE THREAD

**Issue by naboo** [spicywebau/craft-neo#526]
#### Description
We have an older Craft 3.3 site which we want to upgrade to 3.7. Problem is that we have a lot of Neo based content and when upgrading Neo creates XXX,XXX jobs "Applying new propagation method to Neo blocks".

What does these do. Can we clear these and run some manual command to "fix" what the job does? As you can imagine it takes forever for the jobs to clear.

Neo version is "spicyweb/craft-neo": "2.7.21" and upgrading to latest version as of today.

**Comment by ttempleton** [comment]
The migration that created the jobs was added because of a bug where changes to a Neo field's propagation method weren't being applied to the field's blocks once the field was saved, which was causing blocks to disappear from sites where they were still supposed to exist (#411). Then the migration was changed to run the jobs on a per-block-structure basis to avoid an error that occurred because the original bug caused blocks to be attached to more than one structure (#421). Since it was necessary to create a job for each structure to avoid that error, it does mean that a large number of jobs can be created.

There isn't a manual command to run since it was meant to be a one-time fix for that particular bug, but I'd be happy to add a command for it. If you've never changed the propagation methods on any of your Neo fields, though, then it'd be fine to just clear the jobs and take no further action.

**Comment by meredevelopment** [comment]
Sorry to hijack but we're hitting this issue too, and the job times-out after 300 seconds so never completes the 9000+ blocks. We're on v2.12.1 at the moment. Will we need to manually delete the migration from the DB as someone else was advised to do in #421?

**Comment by ttempleton** [comment]
@meredevelopment If you've ever changed a Neo field's propagation method, do try to delete the migration and rerun it. If that still happens when rerunning it, please let me know.
