### ISSUE TITLE
Nested blocks jumping out of parent block

### ISSUE THREAD

**Issue by rstix** [spicywebau/craft-neo#528]
#### Description
We ran the update that you introduced but the issue still persists.
We have Neo field with nested blocks. If some of them are added to the entry and saved the nested blocks are jumping out of the parent block and then the entry is not rendering:
![image](https://user-images.githubusercontent.com/23715446/146052192-81f06e35-271c-4707-bf36-3da9b0762869.png).

Here is how it looked before saving:
![image](https://user-images.githubusercontent.com/23715446/146051321-29a065d7-8488-4935-b453-bdf49256a3c1.png)

#### Steps to reproduce
I am able to reproduce it locally, but it is still occurring only if signed in as a particular user. Please let me know where should I send the database and the composer files? I tried to contact you at this (plugins@spicyweb.com.au) email but I got no response.

#### Other information
- Neo version: 2.11.21
- Craft version: 3.7.24

**Comment by ttempleton** [comment]
Sorry for missing that @rstix, the plugins address is checked for emails when I'm notified here to expect one — which was not the case in #510 once it was closed with no new activity since then. I'll be clearer with my wording in the future, but when I say something like "If the issue persists, let me know and I'll reopen it", please do let me know here on GitHub.

Going to close this issue in favour of reopening #510. In the meantime, could you please resend your database to the plugins address (and let me know in #510 once you've done so) as the link you've sent through isn't working.
