### ISSUE TITLE
Restoring trashed entry restores child blocks as parent blocks + blocks only restoring on current site

### ISSUE THREAD

**Issue by bavodeclercq** [spicywebau/craft-neo#533]
#### Description
We have a multisite setup with custom propagation method entries. When removing an entry and restoring that entry, three problems arise:
1. Child blocks are now parent blocks on the current site.
2. Blocks are duplicated on the current site
3. The blocks restore only to the current site. There are no more blocks on the other sites.

[Screenshot](https://user-images.githubusercontent.com/2085698/150780847-b36780e1-0ee6-4d85-9147-55dad653db0d.png)

#### Steps to reproduce
1. Add Neo block with subblocks to site A and B
2. Remove entry (while on site B)
3. Restore entry (while on site A)

#### Other information
- Neo version: 2.12.2
- Craft version: 3.7.30.1
- What is the affected Neo field's propagation method: none
- Is eager-loading used? Yes

**Comment by ttempleton** [comment]
Thanks for reporting that! The blocks not restoring in the correct place or not restoring at all has now been fixed in Neo 2.12.3. I didn't experience any block duplication while looking into it, but I believe the other fixes would have fixed that as well. If that's not the case, please let me know.
