### ISSUE TITLE
Fields No Longer In Tabs

### ISSUE THREAD

**Issue by brianrivet-tilt** [spicywebau/craft-neo#552]
I'm having an issue where fields that I have in a Neo field that were in tabs in Craft 3.7.36/Neo 2.12.5 are no longer in tabs in Craft 3.7.37/Neo 2.13.0. The problem also doesn't resolve itself when Neo is updated to 2.13.2.

**Comment by ttempleton** [comment]
Do you mean that the fields have all merged into one tab, or the fields have been removed entirely? There was a migration in 2.13.0 that resaved block types to add their group IDs, but that should not have removed fields or merged all fields into one tab.

**Comment by brianrivet-tilt** [comment]
All the fields are still present and they still save their values, but they are merged into a single tab and the tabs that were there are not there anymore (as opposed to still being present but with no fields in them).

**Comment by ttempleton** [comment]
For an affected block type, could you please provide an example of how the field layout was set before upgrading, compared with after? Just trying to get an idea of whether there's some configuration that Neo isn't saving properly.

In the meantime I'll make a change to the migration to only set the groups each block type belongs to in the project config instead of resaving the block types.

**Comment by ttempleton** [comment]
The 2.12.5 project config files don't seem to include the Neo block types, but judging by the screenshots, you were making use of blank tabs. Unfortunately, due to changes in how field layouts work from Craft 3.5 onwards, we were unable to support blank tabs in Neo block type field layouts from Neo 2.8 onwards; existing blank tabs would be kept until the next time the block type was saved, at which point the blank tabs would be removed, which seems like what's happened here.

I've had another look at it today and I've made a change that will keep the blank tabs when applying the migration from 2.13.0, or when applying a project config that still includes blank tabs, and I've released 2.13.3 with that change. Unfortunately it's still the case that resaving the Neo field through the Craft control panel will cause the blank tabs to be lost, since the blank tabs can't be included in the field layout data that gets sent to the server. So I recommend adding UI elements to your blank tabs to make sure they're kept (e.g. the child blocks UI element may be a good solution for the setup in the screenshots).
