### ISSUE TITLE
Memory Allocation Error on field settings page after upgrade

### ISSUE THREAD

**Issue by myleshyson** [spicywebau/craft-neo#580]
#### Description
I've been trying to debug this the last few days and struggling to figure out what's going on. I upgraded my craft installation to 4.0.2 and neo to 3.0.4. Everything seems to work ok until I go to edit our only neo field. When trying to access the field setting for that neo field, the request hangs up and I eventually get a memory allocation error. 

Used Xdebug and found that the problem function seems to be in `benf\neo\assets\SettingsAsset:110`.  

This also happens when trying to create a new neo field. When selecting neo from the field type list, the field setting request just hangs. 

We have a particularly large neo field with like 12 block types in it, so that also might be contributing. Though I think it might be something else since it loaded almost instantly in Craft 3. 

#### Steps to reproduce
1. Upgrade Craft 3 to Craft 4 with an existing neo field
2. Try to go to that neo fields settings.

#### Other information
- Neo version: 3.0.4
- Craft version: 4.0.2

**Comment by JansenLukas** [comment]
I got a likewise performance issue after upgrading from craft 3 to 4, when opening the field settings it takes a really long time to load, if I look in the craft debug toolbar there are a lot of request to get all the new condition rules for the fields.

On the other side the frontend did have a really big performance improvement on loading times.🎉

**Comment by myleshyson** [comment]
Yea I just upped my ini settings and it after loading for 4-5 minutes it finally rendered. Since the actual hangup happens in Crafts `\craft\web\twig\variables\Cp::fieldLayoutDesignerHtml` I can't tell yet if this issue is with neo or Craft.

**Comment by ttempleton** [comment]
There were some changes for the Craft 4 version of Neo so that each block type's field layout designer is individually rendered (previously, we were just rendering an empty field layout designer and populating the existing field layouts in JavaScript). So there is some more work Neo is doing behind the scenes now - that said, taking five minutes to load is _somewhat_ excessive...

Anyway, I've just done a test upgrading to Craft 4 with a Neo field with 15 block types, and didn't experience any errors or performance issues. @myleshyson, @JansenLukas, if you can reliably reproduce this, could one of you please send a database backup and composer.json/lock files to plugins@spicyweb.com.au and we'll have a look at it.

**Comment by thupsi** [comment]
I can also confirm that Iexperienced similar issues (very slow loading times for the field edit page). Nothing close to 5 minutes, but still way slower than Craft 3. Front end / entry edit much faster though!

**Comment by myleshyson** [comment]
Opened up an issue in craft core as well since the bottleneck seems to mainly come from their Cp helper class.

**Comment by mihob** [comment]
Same issue here. The neo field editor page is much much slower than in Craft 3

**Comment by ttempleton** [comment]
Great to hear about the performance improvement on Craft's end. I'm still personally not happy with Neo field settings taking 7 seconds to load because of rendering all of the field layout designers, since it should be expected that Neo fields could have many block types with many subfields, and presumably at that point you're not going into the Neo field settings page to edit every block type's field layout at once. So I'll have a look at lazy loading the field layout designers for the Neo 3.1 release.

**Comment by ttempleton** [comment]
I've added lazy loading of field layout designers in the [enhancement/lazy-load-flds](https://github.com/spicywebau/craft-neo/tree/enhancement/lazy-load-flds) branch and it'll be included in Neo 3.1. I'll comment here again when Neo 3.1 is released, it should be later this month.

**Comment by ttempleton** [comment]
Just released Neo 3.1.0 with the field layout designer lazy loading. Hopefully that's the last of the performance issues with Neo field settings, but please let me know if you're still experiencing any performance issues.
