### ISSUE TITLE
Instructions field for Neo block

### ISSUE THREAD

**Issue by Delonvdv** [spicywebau/craft-neo#62]
It would be great to have an instruction field on each Neo block, the same as is available for the Matrix blocks. When building templates for clients, it would be nice to leave a little info for them. Eg: 'This block toggles between 1 and 2 columns, and only accepts text' etc

**Comment by benjamminf** [comment]
It's an interesting idea, but I'll have to think about whether it's something I want to add to Neo. In the meantime, you can accomplish something like this using the [Field Notes plugin](https://topshelfcraft.com/lagniappe/fieldnotes) which will let you add static text to the top of your blocks.

**Comment by sgtpenguin** [comment]
This would be nice!

**Comment by ttempleton** [comment]
I'm going to close this as `wontfix` from a Neo-specific implementation perspective, because it'll be possible to do this with the new field layout designer coming to Craft 3.5, and the UI elements you'll be able to add to a field layout.  In particular, the Tip element seems like it would suit this purpose perfectly.
