### ISSUE TITLE
Undefined array key 1 with Neo 3.3.6 

### ISSUE THREAD

**Issue by zizther** [spicywebau/craft-neo#645]
#### Description
I have updated to Neo 3.3.6, when trying to save an entry in certain sections with a Neo field I am getting this error `Undefined array key 1` in `vendor/spicyweb/craft-neo/src/validators/FieldValidator.php - Line 161`
These are entries from a certain section which already have content in the Neo field blocks, the error has only happened since updating to Neo to 3.3.6

I have tested this in multiple sections with the same field which all have existing content, the error does not always happen in all section, only certain ones.
When creating a new entry in the affected section it saves fine.

#### Other information
- Neo version: 3.3.6
- Craft version: 4.2.3

**Comment by ttempleton** [comment]
Is there a specific sequence of actions you can make on the Neo field that reliably cause the error?

**Comment by zizther** [comment]
@ttempleton I have updated my original description to give more detail.

I can't say specifically about sequence. All I have done is update Neo and another plugin, added 2 Matrix fields to the section in question. For some reason existing entries in this section get the error, but new entries in this section don't.
Other entries in different section which contain this Neo field will resave fine.

Odd that it only appears on entries in a particular section which contain content in the Neo blocks

**Comment by zizther** [comment]
If I downgrade to Neo 3.3.5 I no longer get this issue.

**Comment by zizther** [comment]
I tested by removing all the revisions and the issue still remains.

**Comment by ttempleton** [comment]
> Odd that it only appears on entries in a particular section which contain content in the Neo blocks

Hmm, yeah, that is strange. If possible, could you please send a database backup and composer.json/lock files to plugins@spicyweb.com.au, along with instructions regarding the section where this happens, and we'll have a look.

**Comment by zizther** [comment]
> Hmm, yeah, that is strange. If possible, could you please send a database backup and composer.json/lock files to [plugins@spicyweb.com.au](mailto:plugins@spicyweb.com.au), along with instructions regarding the section where this happens, and we'll have a look.

I've sent this through for you.

**Comment by ttempleton** [comment]
Thanks for sending that. It turns out the error is due to the affected entries having blocks at the top level, whose block types are set not to be allowed at the top level. Presumably these block types were allowed at the top level at some point in the past, and were allowed to stay there since this setting is currently only enforced on the client side.

I'm happy to add a fix for this, to ignore non-top-level blocks existing at the top level when validating Neo fields based on block types' Min Sibling Blocks of This Type setting (which is where this error occurs), since at this point, enforcing the top level setting server-side is arguably a breaking change. But I just wanted to give you this explanation first, in case those block types should be set to be allowed at the top level.

**Comment by zizther** [comment]
Thanks for looking into this.

You are correct. We are in the middle of some updates and transitioning some of the blocks into groups and some of them are no longer top level.
As I understand the issue now, there is no need to put in a fix to deal with this. I can limit Neo to 3.3.5 until content has all been updated correctly.

**Comment by ttempleton** [comment]
I've since realised that this error would still happen anyway once we validate the top level setting server-side, since the min sibling blocks of type validation relies on knowing which block types are valid for a parent block type or at the top level. So I've added a fix for the next release, where the min sibling blocks validation just ignores blocks that exist in places they aren't supposed to exist any more.

**Comment by zizther** [comment]
Great stuff.
Appreciate you looking into this more.

**Comment by benediktblank** [comment]
Stumbled upon that issue today as well. We could not save any old entries that use NEO since the update to 3.3.6.
We downgrade now back to 3.3.5.

**Comment by ttempleton** [comment]
@benediktblank I recommend checking if any top-level Neo blocks in those entries are of block types that are no longer allowed at the top level, or if any nested blocks are no longer valid child blocks based on their parent's allowed child block types. The next Neo release 3.3.7 will resolve that error and allow those fields to save for now, but they will fail validation in Neo 4.

**Comment by ttempleton** [comment]
Just released 3.3.7 with the fix for this.
