### ISSUE TITLE
Migration Error on Upgrade 2.13.15 to 3.3.7

### ISSUE THREAD

**Issue by matthew-macgregor** [spicywebau/craft-neo#649]
#### Description

While upgrading from Neo `2.13.15` to `3.3.7` (as part of the Craft 3 => 4 migration), we are encountering the following issue while running migrations.

```sh
applying m220511_054742_delete_converted_field_block_types_and_groups
Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'neoblocktypes.enabled' in 'where clause'
```

From what I can tell, `neoblocktypes.enabled` was added in a migration here: https://github.com/spicywebau/craft-neo/blob/main/src/migrations/m220812_115137_add_enabled_column_to_block_types.php

But it must be referenced elsewhere that is pulling it in as part of the `m220511_054742_delete_converted_field_block_types_and_groups`. It's very possible that I'm missing something; perhaps there's a workaround?

#### Steps to reproduce

I am reproducing this with a copy of our dev database running the latest Craft 3 and Neo, then following the [upgrade steps for Craft 4](https://craftcms.com/docs/4.x/upgrade.html#performing-the-upgrade). I've also experimented with upgrade to intermediate versions of Neo (`3.0.0`, `3.1.0`, etc.) but that also didn't work.

1. Install Neo `2.13.15`
2. Update Craft to `^4.0.0` and Neo to `3.3.7`
3. `composer upgrade`
4. `craft migrate/all`

#### Other information
- Neo version: `2.13.14` => `3.3.7`
- Craft version: `3.7.53.1` => `4.0.0`
- (if multi-site) What is the affected Neo field's propagation method: n/a
- Is eager-loading used? I'm not sure

**Comment by ttempleton** [comment]
Thanks for reporting that! It turned out that if any Neo fields had been converted to Matrix in the past, then the migration to delete the leftover Neo data, when deleting the Neo blocks, would end up running code checking if the blocks' types were enabled, without first checking if the enabled column actually existed yet.

I've just fixed that for the next release. In the meantime, you can get the fix by setting your composer.json file's `spicyweb/craft-neo` requirement to `3.x-dev as 3.3.7` and running `composer update`.

**Comment by matthew-macgregor** [comment]
Confirming that this resolved the issue for me. I started fresh from our dev database, used the `3.x-dev` version of Neo, upgraded all the plugins, ran the migrations, and it succeeded.

**Comment by ttempleton** [comment]
Neo 3.3.8 has just been released including the fix for this.
