### ISSUE TITLE
Craft 3 Sites failing to update

### ISSUE THREAD

**Issue by brianrivet-tilt** [spicywebau/craft-neo#665]
#### Description
When I try to run updates on a few Craft 3.7.x sites running Neo 2.13.15 I get the following error:

Neo is installed with schema version of 2.13.0 while 2.11.6 was expected.

#### Other information
- Neo version: 2.13.15
- Craft version: 3.7.X (meaning various sub versions of 3.7
- (if multi-site) What is the affected Neo field's propagation method: not applicable
- Is eager-loading used? in some cases

**Comment by ttempleton** [comment]
I don't think this would've been caused by Neo, since plugins set their schema versions but aren't responsible for updating the schema version in the database and project config - but if you can give me more details of the steps you took that led to this error, I can try to point you in the right direction.
