### ISSUE TITLE
Error while applying new propagation method: Unable to duplicate “1234” to site 2: Attempting to duplicate an element in an unsupported site.

### ISSUE THREAD

**Issue by luke-nehemedia** [spicywebau/craft-neo#669]
#### Description
As described here (#668) I am currently removing a lot of translations from fields. Thereby I also changed the propagation method of a big neo field from `Only save blocks to the site they were created in` to `Save blocks to all sites the owner element is saved in`. This results in a queue job "Applying new propagation method to Neo blocks":

``{
    "description": "Applying new propagation method to Neo blocks",
    "elementType": "benf\\neo\\elements\\Block",
    "criteria": {
        "fieldId": "298"
    }
}``

At around 7% is fails. The queue job shows the following error:
> Invalid owner ID: 273710

In the logs, I found:
>  [232050] Applying new propagation method to Neo blocks (attempt: 1, pid: 9901) - Started
> Warning: Unable to duplicate “265726” to site 2: Attempting to duplicate an element in an unsupported site.
> Error: craft\errors\UnsupportedSiteException: Attempting to duplicate an element in an unsupported site. in /home/web1/files/craft3/vendor/craftcms/cms/src/services/Elements.php:1201
Stack trace: [...]
> Warning: Unable to duplicate “268031” to site 2: Attempting to duplicate an element in an unsupported site.
> Error: craft\errors\UnsupportedSiteException: Attempting to duplicate an element in an unsupported site. in [...]
> Warning: Unable to duplicate “268674” to site 2: Attempting to duplicate an element in an unsupported site.
> Error: craft\errors\UnsupportedSiteException: Attempting to duplicate an element in an unsupported site. in [...]
> Warning: Unable to duplicate “270927” to site 2: Attempting to duplicate an element in an unsupported site.
> Error: craft\errors\UnsupportedSiteException: Attempting to duplicate an element in an unsupported site. in [...]
> Warning: Unable to duplicate “271890” to site 2: Attempting to duplicate an element in an unsupported site.
> Error: craft\errors\UnsupportedSiteException: Attempting to duplicate an element in an unsupported site. in [...]
> Warning: Unable to duplicate “271942” to site 2: Attempting to duplicate an element in an unsupported site.
> Error: craft\errors\UnsupportedSiteException: Attempting to duplicate an element in an unsupported site. in [...]
> Warning: Unable to duplicate “273711” to site 3: Attempting to duplicate an element in an unsupported site.
> Error: craft\errors\UnsupportedSiteException: Attempting to duplicate an element in an unsupported site. in [...]
> Error:  [232050] Applying new propagation method to Neo blocks (attempt: 1, pid: 9901) - Error (time: 26.256s): Invalid owner ID: 273710

Any ideas why this is happening and how it can be resolved?

#### Other information
- Neo version: 2.13.15
- Craft version: 3.7.59
- (if multi-site) What is the affected Neo field's propagation method: Only save blocks to the site they were created in → Save blocks to all sites the owner element is saved in
- Is eager-loading used? No

**Comment by ttempleton** [comment]
You might need to use the [`neo/fields/reapply-propagation-method`](https://github.com/spicywebau/craft-neo/blob/2.13.15/docs/console-commands.md#neofieldsreapply-propagation-method) console command:

```sh
php craft neo/fields/reapply-propagation-method --by-block-structure
```

There was a bug in older versions of Neo that can cause this error in later versions, if you're applying propagation methods to blocks without using the `--by-block-structure` option. It only needs to be done once, and it was originally run as a migration, but it was moved to a console command because we had a few people concerned about the large number of queue jobs it generates.

Please let me know if that works!

**Comment by luke-nehemedia** [comment]
Thank you for the quick answer. 

Unfortunately it did not resolve the issue. I ran the command, but I just got the output `0 new jobs were added to the queue.`. I tried to re-run the failed queue. Same result.

**Comment by ttempleton** [comment]
Ah, sorry, yes, the command won't add any jobs for fields with the propagation method set to "Save blocks to all sites the owner element is saved in". You'll need to set the field's propagation method back to "Only save blocks to the site they were created in" first, then run the command, then set it back to "Save blocks to all sites the owner element is saved in".

**Comment by ttempleton** [comment]
Hmm, I'm not really sure why that's happening, then. If possible, could you please send your composer.json/lock files and database backup to plugins@spicyweb.com.au, and we'll have a look.

**Comment by luke-nehemedia** [comment]
I just sent you the requested files via email. Thank you very much for your help.

**Comment by ttempleton** [comment]
Thanks for sending that @luke-nehemedia. I'm not seeing any of the "Attempting to duplicate an element in an unsupported site" errors, so I'm assuming that running the console command has fixed that.

Regarding the "Invalid owner ID" errors, it turned out that the owners of the Neo blocks giving that error were all Solspace Calendar events, belonging to the same calendar. For some reason, those events only exist for one site despite the calendar being enabled for all sites. A few of these Neo blocks somehow actually have content saved in the database for the other sites, so trying to resave those blocks causes the error.

I'm not sure what's happened to cause the events to only exist for one of the sites they should be saved for, but that seems to be the root of the problem. As far as the excess Neo block content is concerned, the following SQL command deletes that content which should allow the propagation method job to complete:

```sql
DELETE FROM craft_content WHERE siteId != 2 AND elementId in (SELECT id FROM craft_neoblocks WHERE ownerId IN (273710, 274844, 274843, 274845, 274848, 274846));
```

Please note that I'm only assuming that this content is unnecessary given that the event doesn't exist for the other sites, and you should check that all content is still there on site 2 if you execute the command.

If the calendar/events shouldn't actually exist for the other sites, then instead of running the above command, just disabling the calendar for the other sites should work. If the calendar/events should exist for the other sites, you may need to open an issue with Solspace Calendar. In the interest of not publicly posting any actual content from your Craft install, the name of the affected calendar can be found with the following command:

```sql
SELECT name FROM craft_calendar_calendars WHERE id = 7;
```
