### ISSUE TITLE
Neo blocks unexpectedly scrambled when reverting to old draft

### ISSUE THREAD

**Issue by gateszies** [spicywebau/craft-neo#694]
### Bug Description

We are experiencing problems with Neo blocks unexpectedly moving around when reverting the content from a previous revision (potential duplicate of our other issue #677).

When our author reverts a page from a previous draft (without any major changes between the two), the structure of the Neo blocks will get scrambled causing the page layout to break. This bug typically moves each nested Neo block down into the next parent block. 
[Screen Record](https://user-images.githubusercontent.com/66807975/208197668-58ffaf02-83fa-4c7a-9e6e-fd9b232aa4f5.mov)

I'm happy to send over another DB backup and our composer files if that's helpful.

### Steps to reproduce

Go to the affected page in Craft
Choose a previous draft under the Recent Revisions dropdown
Hit Revert content from this revision
Blocks are scrambled

### Expected behaviour

Entry should revert to the older draft without content blocks being scrambled.

### Neo version

3.5.13

### Craft CMS version

4.3.5

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
> I'm happy to send over another DB backup and our composer files if that's helpful.

Thanks - could you please send those to plugins@spicyweb.com.au and we'll have a look at it.

**Comment by ttempleton** [comment]
Thanks for sending those files in. It turned out that in some cases the revision blocks were getting the wrong information about which level they should be saved at (though otherwise being saved in the correct order), and that's now fixed in Neo 3.5.14.

Unfortunately, that then means the reverted versions of those blocks are also saved at the wrong level, so they would need to be fixed by dragging them back to the correct place.
