### ISSUE TITLE
Option to use Neo-specific fields

### ISSUE THREAD

**Issue by chasegiunta** [spicywebau/craft-neo#70]
>A Matrix-like field type that _uses existing fields_

At this point, Neo is so much more than this: Tab Organization, Block Grouping, Nestable Blocks, etc.

Neo is so incredibly powerful, I've come to realize that my field count can jump up pretty high (with the help of Quick Field) _really_ fast.

Not sure how the UX would fit, but would it be possible (or wanted by anyone else other than me) to have the option to create Neo-specific fields (like Matrix)? It would have to use the field layout manager with both existing & Neo-specific fields, which could also be problematic development-wise.

It might be too much trouble than it's worth. The Pro's would be it would cut down on the potentially massive field list that are meant only for a single Neo field, and also avoid naming conflicts with existing fields used in other contexts outside Neo.

**Comment by 23d1** [comment]
I think that's one of the main features of Neo, in terms of being able to reuse existing fields in multiple neo fields. I group all that stuff into field groups. If you want similar functionality but less clutter under Settings > Fields (which doesn't really matter to be honest, as only an admin should have access to that stuff anyways) you could use SuperTable with Matrix fields. I did that prior to using Neo for the same functionality—Neo is so much nicer though, just because you don't have to have those fields baked into a field (not being able to reuse, and also caused me quite a bit of headache with database and so forth). You also don't have to dive into a deep layer of fields to change something like a description, or even functionality. Just do it in one spot and it updates across multiple Neo fields.

**Comment by ChaseGiunta** [comment]
@23d1 
>I think that's one of the main features of Neo

It is! I'm not requesting to change that. I _need_ that functionality. Which is also why the fields would have to live along side the existing fields in layout-editor. The **real** reason for my concern here is _the amount of columns being added to my content table_ with my very elaborate (yet flipping awesome!) Neo field(s). 

Again, quite possibly a pipe-dream and more effort than it's worth.

**Comment by Emkaytoo** [comment]
@ChaseGiunta What's the use case you're going for? There might be another solution but I'm not sure what the practical case is. Are you just looking to reduce your field count?

This may not apply to you, but one thing that I had to learn to get used to (coming from an EE environment) is reusing fields in general. In EE you had `headline_products` and `headline_services` as two separate fields, whereas in Craft we've been reusing fields, both in Neo and in regular models. This may be an insultingly simple answer (apologies), but I remember having that though when I first started with Craft until my developer said "Duh, just reuse them."

**Comment by benjamminf** [comment]
@ChaseGiunta At the beginning, I had considered whether to separate Neo fields from the general fields, but having another field manager seemed too much. The alternative was to give Neo block types their own content tables in the database. But given how Craft's fields system works, each block type's table would need to have every field as a column anyway, kind of defeating the purpose.

I think @Emkaytoo has the right idea. In terms of field counts, I think it's a mostly a matter of planning what fields you need and how you want to use them right from the beginning, as opposed to creating them as you go along.

In practice, what I tend to do is create fields for specific purposes/modules rather than contexts – so for example, I have a group of fields for content like "Headline", "Body Text", and "Summary" in my "Text" field group, and use them in both Neo blocks and entry types. I then use Relabel to amend the instructions if I need to. I also have groups like "Media" and "Slideshow".

For my purposes, this works well. Although I usually start out with relatively a lot of fields, I find additional sections/blocks/etc rarely require creating new fields.

**Comment by ChaseGiunta** [comment]
@benjamminf Fair enough :) I've gone down the relabel / single-field-multiple-cases route before so I'm quite familiar with it. Just a suggestion to get alleviate some of that. I'll let you close if you think it should be off the table / outside Neo's scope.

**Comment by benjamminf** [comment]
@ChaseGiunta I think this is an interesting discussion to have though, and I'm starting to plan out Neo for Craft 3 soon, which will be essentially a complete rebuild. There might be an elegant and memory efficient solution I haven't thought of.

**Comment by ttempleton** [comment]
The future plans for Craft and Matrix fields involve [using global fields](https://speakerdeck.com/brandonkelly/future-of-craft?slide=25) rather than their own specific fields.  Presumably, Craft's `fields` table's `context` column would be removed at the same time, since it mainly exists to allow Matrix fields to have their own fields, so that would remove the possibility for Neo to have its own fields as well.  Personally, I think it'd be great if Neo could do both, but at this stage it seems likely that, if we were to implement this, we'd have to remove it in the future, so there's probably not much point any more.
