### ISSUE TITLE
Eager loading a field nested in multiple blocks

### ISSUE THREAD

**Issue by MarcusGaius** [spicywebau/craft-neo#715]
### What question would you like to ask?

I have an assets field that is nested in more than one block of a neo field. I am trying to make an eager load map that would include all instances of that field, but all it ends up doing is repeating the same query for every reference to that field, even though it's nested in different blocks.

In addition to eagerly loading the neo field/blocks, I also want to eagerly load the associated image transforms.

Is there a prescribed way of doing it right?

**Comment by ttempleton** [comment]
Eager loading relational fields in Neo blocks should work exactly the same as with [Matrix blocks](https://craftcms.com/docs/4.x/dev/eager-loading-elements.html#eager-loading-elements-related-to-matrix-blocks) - with the exception that [you would need to use Neo blocks' `useMemoized()` method, to give each block its own local database of blocks to query, if you have any child blocks](https://github.com/spicywebau/craft-neo/blob/2a551a3a6691f461ed758325f471b55cc088c567/docs/eager-loading.md#with-hierarchy) (please note that `entry.neoField` in the linked documentation refers to an already eager loaded array of Neo blocks).

If that isn't working, if possible, could you please share your code for your eager loading and I'll have a look at what's happening.

**Comment by dominikkrulak** [comment]
[Following this example](https://github.com/spicywebau/craft-neo/blob/main/docs/eager-loading.md#complete-example) and starting off like this:
```
{% do craft.app.elements.eagerLoadElements(
	className(entry),
	[entry],
	[
		'neoField.blockTypeHandle:component.matrixField'
	]
) %}
{# ... the rest of example #}
```
and my `matrixField` have an _asset field_, how would I approach eager-loading of that _asset field_? Or is it eager loaded already in the "local database" and no need to use `with()` parameter when inside the child block?

Using `dump()` function I can see that the `component` block type is included in `_eagerLoadedElements` with empty array of `items` key and I wonder If `{% do block.useMemoized(blockType) %}` should also be used inside child blocks?

**Comment by ttempleton** [comment]
@dominikkrulak Your initial `useMemoized()` loop should give every Neo block in the Neo field a reference to every other block in the field, so no need to redo `useMemoized()` afterwards.

If your Matrix block type handle is `component`, then you would need to eager load the Matrix field with `'neoField.component:matrixField'`, rather than `'neoField.blockTypeHandle:component.matrixField'`. If your Matrix block type has the handle `assetsBlock` and your assets field has the handle `assetsField`, you would then also need to eager load `'neoField.component:matrixField.assetsBlock:assetsField'`. I'll update the docs soon to clear that up.

**Comment by dominikkrulak** [comment]
@ttempleton, Thank you for clarifying that up :)
