### ISSUE TITLE
creating an query for an individual block 

### ISSUE THREAD

**Issue by jacksoncool** [spicywebau/craft-neo#729]
### What question would you like to ask?

Hi, 

Can I write a query for 1 individual block in a neo field that is saved to a specific entry?

**Comment by ttempleton** [comment]
If you have the block's ID, you can query for that one block. This would normally involve passing the query the block's ID as well as the site ID if it's a multi-site Craft project. However, due to the bug #682, you would (until I can figure out how to fix that without breaking other stuff...) also need to pass the owner ID to get the correct block structure and prevent duplicate block data.

PHP example:

```php
use benf\neo\elements\Block;

$block = Block::find()
    ->id($blockId)
    ->siteId($siteId)
    ->ownerId($entryId)
    ->one()
```

Twig example:

```twig
{% set block = craft.neo.blocks()
    .id(blockId)
    .siteId(siteId)
    .ownerId(entryId)
    .one()
%}
```

Let me know if you have any further questions.
