### ISSUE TITLE
Js errors after saving entries with validation errors

### ISSUE THREAD

**Issue by mihob** [spicywebau/craft-neo#746]
### Bug Description

I have an entry with several Neo fields.  As soon as I trigger somehow an validation error in one of the fields of the entry I get the following Javascript error:

<img width="475" alt="image" src="https://github.com/spicywebau/craft-neo/assets/48485580/3477830d-8ec1-472f-84ee-fc1bc59631a9">

After that, the UI of the entry is no longer usable. Due to the Javascript error, it is not even possible to reset the changes. However, I can change the language of the entry and then discard the changes there.

I know that the error comes from Redactor, but the problem only occurs with entries with Neo fields.  And in this case it also seems to occur with Neo blocks with Redactor fields.

### Steps to reproduce

1. Trigger an validation error

### Expected behaviour

No Javascript error should occur.

### Neo version

3.7.9

### Craft CMS version

 4.4.13

### What is the affected Neo field's propagation method?

Save blocks to all sites the owner element is saved in

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
I was unable to reproduce the Redactor field error, but while trying to reproduce it, I did find and fix [another bug](https://github.com/spicywebau/craft-neo/commit/b333d1e2a17da39c1e262ffe1de363ec3dc641cd) that could be related.

Could you please set your composer.json file's `spicyweb/craft-neo` requirement to `3.x-dev as 3.7.9`, run `composer update` and let me know if that resolves your issue as well?

**Comment by mihob** [comment]
No, unfortunately that did not solve the problem.

I have tried something else.  The error seems to occur as soon as a new draft is created.

If I change any field (without saving) and then reload the entry page with the draft, the error also appears, even if everything is valid.

The save button can still be clicked, but the following error appears:

<img width="338" alt="image" src="https://github.com/spicywebau/craft-neo/assets/48485580/f3c8659f-8311-4d9d-ad6d-7940aa99b77f">

The error is somewhat difficult to reproduce and actually only occurs with one entry type. 

Just out of interest, the error you fixed, did it cause blocks to be duplicated?

**Comment by ttempleton** [comment]
I didn't see block duplication, but I saw duplication of the 'add block' buttons (and none of them seemed to function) due to a bad JQuery selector - I didn't have any child blocks on that entry, but I wouldn't be surprised if it caused child blocks themselves to be duplicated.

If possible, could you please send a database backup and your composer.json/lock files to plugins@spicyweb.com.au, along with an example of an entry from that entry type that has this issue, and we'll have a look.

**Comment by mihob** [comment]
I wrote you an email, hope it helps

Sorry for my late reply, I didn't make it earlier.

**Comment by ttempleton** [comment]
Thanks for sending that @mihob. The issue turned out to be that the created provisional draft ended up with no block structures for the Neo fields on the primary site. Since another provisional draft exists for the affected entry, which does have block structures for the primary site (presumably there were changes to the Neo fields in that draft), querying the blocks when reloading the element editor page then invoked issue #682 causing block duplication, which then caused the JS errors. That should be fixed now in Neo 3.7.11.
