### ISSUE TITLE
Neo Blocks deleted after save field

### ISSUE THREAD

**Issue by alexanderloewe** [spicywebau/craft-neo#747]
### Bug Description

After several attempts to save a Neo field, I always get this error message and many of the blocks inside the field have disappeared.

That only happens with a specific field, not with all Neo field in the installation.
```
yii\base\ErrorException: Undefined array key "topLevel" in /Users/office/_localhost/tecti/vendor/spicyweb/craft-neo/src/Field.php:338
Stack trace:
#0 /Users/office/_localhost/tecti/vendor/craftcms/cms/src/web/ErrorHandler.php(79): yii\base\ErrorHandler->handleError(2, 'Undefined array...', '/Users/office/_...', 338)
#1 /Users/office/_localhost/tecti/vendor/spicyweb/craft-neo/src/Field.php(338): craft\web\ErrorHandler->handleError(2, 'Undefined array...', '/Users/office/_...', 338)
#2 /Users/office/_localhost/tecti/vendor/yiisoft/yii2/base/Component.php(180): benf\neo\Field->setBlockTypes(Array)
#3 /Users/office/_localhost/tecti/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\Component->__set('blockTypes', Array)
#4 /Users/office/_localhost/tecti/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(benf\neo\Field), Array)
#5 /Users/office/_localhost/tecti/vendor/craftcms/cms/src/base/Model.php(78): yii\base\BaseObject->__construct(Array)
#6 /Users/office/_localhost/tecti/vendor/spicyweb/craft-neo/src/Field.php(191): craft\base\Model->__construct(Array)
#7 [internal function]: benf\neo\Field->__construct(Array)
#8 /Users/office/_localhost/tecti/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#9 /Users/office/_localhost/tecti/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('benf\\neo\\Field', Array, Array)
#10 /Users/office/_localhost/tecti/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('benf\\neo\\Field', Array, Array)
#11 /Users/office/_localhost/tecti/vendor/craftcms/cms/src/Craft.php(54): yii\BaseYii::createObject(Array, Array)
#12 /Users/office/_localhost/tecti/vendor/craftcms/cms/src/helpers/Component.php(122): Craft::createObject(Array)
#13 /Users/office/_localhost/tecti/vendor/craftcms/cms/src/services/Fields.php(593): craft\helpers\Component::createComponent(Array, 'craft\\base\\Fiel...')
#14 /Users/office/_localhost/tecti/vendor/craftcms/cms/src/controllers/FieldsController.php(338): craft\services\Fields->createField(Array)
#15 [internal function]: craft\controllers\FieldsController->actionSaveField()
#16 /Users/office/_localhost/tecti/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#17 /Users/office/_localhost/tecti/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#18 /Users/office/_localhost/tecti/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('save-field', Array)
#19 /Users/office/_localhost/tecti/vendor/craftcms/cms/src/web/Application.php(304): yii\base\Module->runAction('fields/save-fie...', Array)
#20 /Users/office/_localhost/tecti/vendor/craftcms/cms/src/web/Application.php(633): craft\web\Application->runAction('fields/save-fie...', Array)
#21 /Users/office/_localhost/tecti/vendor/craftcms/cms/src/web/Application.php(283): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#22 /Users/office/_localhost/tecti/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#23 /Users/office/_localhost/tecti/web/index.php(21): yii\base\Application->run()
#24 {main}
```

### Steps to reproduce

Tested local and on cloud multiple times.

### Expected behaviour

-

### Neo version

3.7.9

### Craft CMS version

4.4.13

### Does this issue involve templating, and if so, is eager-loading used?

This is a templating issue, and eager loading is used

**Comment by corneliusio** [comment]
I believe we may also be seeing this or a related issue on one of our sites. We suddenly had a number of entries' Neo blocks disappear both in the dashboard and on the front-end. The reason I believe it could be related despite the fact that we are not seeing this error is that I was able to find a workaround for getting the blocks to show back up on the front-end (not the back-end though). Because we're eager loading, we have a check in our blocks loop to evaluate `block.level == 1`. However, when I debug the loaded modules (which ARE being returned by the `entry.neoBlockField.all` query), their level is not an integer but instead just `null`. If I update the loop to allow either `level == 1 or level == null` than we get the blocks to show up as expected. This obviously doesn't do anything for the dashboard though, so if a client saves a page with missing blocks they may end up getting deleted.

All that to say, the thread tying these together appear to be the `level` property. If this ends up being unrelated, I'm happy to open a separate issue.

### Neo version
3.7.9

### Craft CMS version
4.4.12

### What is the affected Neo field's propagation method?
Only save blocks to the site they were created in

Does this issue involve templating, and if so, is eager-loading used?
Yes and yes.

**Comment by ttempleton** [comment]
@alexanderloewe If possible could you please send in your composer.json/lock files and database backup to plugins@spicyweb.com.au and let us know which field this is happening with, and we'll have a look. If it's the same Craft project as issue #750, please also let us know which entry that is happening with and we'll have a look at that as well.

**Comment by ttempleton** [comment]
I'd be interested to know whether this issue still occurs with Neo 3.8.0, now that block type settings are lazy loaded.

If it does still occur, could you please provide a list of steps you can take, from first loading the Neo field settings page, that reliably reproduce the issue?

**Comment by ttempleton** [comment]
Closing this issue for now, due to inactivity, but please let me know if the issue persists and I'll reopen it.
