### ISSUE TITLE
Fields changing their Type

### ISSUE THREAD

**Issue by alexanderloewe** [spicywebau/craft-neo#750]
### Bug Description

We have the problem that fields are changing their Type, see in the Video:

https://github.com/spicywebau/craft-neo/assets/69263307/31a3e898-0e3e-468b-9359-f9cd9e6bd83d

### Steps to reproduce

Update

### Neo version

3.7.9

### Craft CMS version

4.4.13

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Thanks for sending those files @alexanderloewe, I've found the entry this was affecting but I can't reproduce this yet.

With the state of the entry as it is now, are you still able to reproduce this? If so, is there a specific set of actions that you can take, from starting to edit the entry, to reproduce it? Feel free to reply via email if there are any private details involved.

This sort of issue has come up a couple of times since 3.7.0, so I'm sure you've found a situation where it happens that I've missed - just not sure how to trigger it yet.

**Comment by ttempleton** [comment]
No need to create another account - but if you're able to reliably reproduce it, then could you please send (either posting here or through email) a capture of another entry where this happens, from the start of editing the entry?

**Comment by ttempleton** [comment]
Closing this issue for now, due to inactivity, but please let me know if the issue persists and I'll reopen it.
