### ISSUE TITLE
Is it possible to Group Child blocks

### ISSUE THREAD

**Issue by sander-lameco** [spicywebau/craft-neo#753]
### What question would you like to ask?

We have a Neo field with loads of content blocks, some of these content blocks contain more than 1 child block.
Is it possible to group the Child blocks per child block instead of having them all in one and the same "matrix"?

For example now we have:
- Content with Item List
  - List item 1
  - List item 2
  - Button 1
  - List item 3
  - Button 2

Would it be possible to get something like:
- Content with Item List
  - List items
    - List item 1
    - List item 2
  - Buttons
    - Button 1
    - Button 2

I see an option called "Group Child Block Types" (Will child block types be shown in their groups?) But this only groups the child blocks in the dropdown I believe?

**Comment by ttempleton** [comment]
If I'm understanding correctly - you would want to create new 'Buttons' and 'List items' block type groups for those block types.

![Screenshot 2023-06-19 at 19-50-21 Create a new field - Craft 4](https://github.com/spicywebau/craft-neo/assets/19421878/06a5a1a4-1290-46a2-bee2-0502fc9e312b)

![Screenshot 2023-06-19 at 19-55-29 Create a new entry (First draft)](https://github.com/spicywebau/craft-neo/assets/19421878/a9c45219-8f77-4988-b0f1-cdf0263ad3f2)

If I've misunderstood, please let me know.

**Comment by ttempleton** [comment]
Ahh, okay. No, there's no way to do that with Neo. Maybe the closest thing to a feature request that sounds like that would be #513 - although that describes putting different child block types under different tabs, but if we were to implement that, it'd make sense to allow different child block types in different places in the same tab as well.

There are no plans to implement that feature request any time soon, though, so if you want to force the buttons and list items to be separate, unless they need child Neo blocks of their own, making them Matrix fields instead of child Neo blocks might be better.
