### ISSUE TITLE
Neo Field Loses All Nesting Structure and Doesn't Conform to Rules in Field Settings for Child Blocks

### ISSUE THREAD

**Issue by brianrivet-tilt** [spicywebau/craft-neo#765]
### Bug Description

I am seeing some weird behavior on a site where I'm using Neo for my content builder. When I look at the entries in the CP for the pages having issues, the blocks in the Neo field are all showing as top level even though they aren't supposed to be, and when I look at it on the front end the pages don't render correctly because of it.

### Steps to reproduce

I don't know how it happened in the first place, it just happened all of a sudden, so I can't tell you how to reproduce it, but I can provide you with database backups of the site having the issue and a backup where it wasn't so you can compare.

### Neo version

3.7.12

### Craft CMS version

4.4.14

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by brianrivet-tilt** [comment]
Just more information, I restored the database for the site using the backup I had that was not showing the issue, and it worked temporarily, but the site is showing thew same problem again, and no one has been in the site editing anything.

**Comment by ttempleton** [comment]
That sounds like the block structure has either been deleted, or never been created e.g. for an applied draft or revision.

Until about two months ago, there was a bug where using Craft's [`runQueueAutomatically`](https://craftcms.com/docs/4.x/config/general.html#runqueueautomatically) setting would cause entry revisions with Neo fields to not have any block structure until the queue was manually run, since they're created for revisions with queue jobs. Is there any chance you're using that setting, and an old revision has been applied? If not, then could you please send in those database backups and your composer.json/lock files to plugins@spicyweb.com.au and I'll see if I can figure anything out.

**Comment by brianrivet-tilt** [comment]
I've sent the files to the email address provided. There were no revisions being applied to any of the pages in question, so I don't think that is the issue. Just FYI, this started after having updated the production site to Neo 3.7.12 from 3.7.9. However, I replaced the database on the production site with a backup that did not have the problems and the issue resurfaced after a few minutes even though no edits were being made on the site. I then restored the backup again and tried upgrading to 3.8.0 and the same thing happened. I then restored the database again and tried rolling back to 3.7.9 and it happened again, so as of now the site cannot display content, as each time I restore a database backup it breaks again shortly thereafter.

**Comment by ttempleton** [comment]
Thanks on sending the files for this. I see this project has Preparse Field installed, which is [incompatible with Neo](https://github.com/spicywebau/craft-neo/blob/f8b7e54f0237c2e18306a41c78930e5b955e0221/docs/plugin-compatibility.md) due to various issues it causes with Neo, including [one other known case of loss of block structure data](https://github.com/craftcms/cms/issues/13256). I'm assuming Preparse Field is causing your issue as well, so I recommended that you disable or remove it. Please let me know if that turns out not to resolve it, though.
