### ISSUE TITLE
Entry Condition with custom fields not persisted

### ISSUE THREAD

**Issue by deeekay** [spicywebau/craft-neo#779]
### Bug Description

Unexpected behaviour when trying to use custom fields for entry condition in neo blocks.

### Steps to reproduce

1. Select a Neo field block and click on "Advanced"
2. Select "Add a rule" from "Entry Condition"
--> Expected: All fields can be selected (under "Fields")
--> Actual: Only default conditions can be selected
4. Select any condition and click on "Add a rule" or on the previously added rule
--> Any field can now be selected
5. Add condition and save neo field
6. Open neo field again and go to "Advanced" and the "Entry Condition" again
--> Expected: previously added rule with custom field is still there
--> Actual: previously added rule is gone

https://github.com/spicywebau/craft-neo/assets/1050619/28ce1583-0cf6-4518-a5a6-f4223b53c6a4

### Neo version

3.8.6

### Craft CMS version

4.5.1

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
It is currently expected that the field condition options would not appear. I'll have a look at why they start to appear, likely next week.

**Comment by ttempleton** [comment]
As far as I can tell, this isn't possible for us to fix by removing the options from the condition builder without an extra event in Craft to help us out (Neo currently using an event when condition rule types are registered, in combination with a flag set in Neo when rendering the block type settings that we're unable to set when the condition builder is re-rendered after a condition is added).

Since it seems unreasonable to me for Craft to have changes made to it to fix one bug in one plugin, I'm going to close this and reopen #778, as that being implemented would make this issue obsolete anyway.
