### ISSUE TITLE
When saving field with empty field layout tab, tab gets duplicated

### ISSUE THREAD

**Issue by piotrpog** [spicywebau/craft-neo#789]
### Bug Description

When saving field with empty field layout tab, tab gets duplicated.

### Steps to reproduce

1. Create neo field, add block type.
2. Add field layout tab, do not add any fields to it, save field.
3. Empty tab gets duplicated, end when resaved again, it gets further duplicated exponentially.

### Neo version

3.9.2

### Craft CMS version

Craft Solo 4.5.6

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
Thanks for reporting this - I'd missed that blank tabs weren't being removed any more in Craft 4.5, so some workaround code we had in place to keep old blank tabs from when we used to be able to independently support blank tabs was no longer needed and was causing this issue. That will be fixed in the next release, most likely within the next day.

**Comment by ttempleton** [comment]
Neo 3.9.3 has now been released.

**Comment by ryssbowh** [comment]
Hi,

I've had the same issue recently and didn't realise until it was too late.
I now have more than 131000 tabs created and I can't delete them manually, the field also won't save before php memory timeout.

Any idea how I would delete all those tabs ?

**Comment by ryssbowh** [comment]
Realised that they all belonged to the same layout, so deleted all of them by that, issue fixed.
