### ISSUE TITLE
Craft CMS 5

### ISSUE THREAD

**Issue by alexanderbuergin** [spicywebau/craft-neo#811]
### What question would you like to ask?

How do you see the future of Neo when Craft CMS 5 hits the market? Since Craft 5 should probably also offer multi-level fields.

Will you provide a migration option from Neo to Matrix?

**Comment by ttempleton** [comment]
Neo will support Craft 5. The main change I'm imagining at this stage, based on the decoupling of entry types and sections in Craft 5, and Matrix block types becoming entry types, is that Neo would still have block types (since we still have a number of block type settings that entry types don't have) but you'd select an entry type to associate with the block type, so the block type uses that entry type's name and field layout. Essentially the idea discussed in issue #100, except it'll be entry types instead of any custom block type templates.

Neo fields can already be converted to Matrix fields as they exist now (and this should happen automatically if you uninstall Neo). When nested Matrix fields were planned for Craft 4, there were plans for [inbuilt migration from Neo](https://github.com/craftcms/cms/discussions/8101#discussioncomment-901148) as part of that, so at this stage I'm guessing that's still planned as part of the work for Craft 5.

**Comment by ttempleton** [comment]
We are currently planning for a stable Neo release for Craft 5 to coincide with the stable release of Craft 5 itself, planned for late March.

There is some early work on it in the [5.x branch](https://github.com/spicywebau/craft-neo/tree/5.x), if you would like to check that out, but be aware that some features might not work properly at this stage.

**Comment by ttempleton** [comment]
I've just released 5.0.0-beta.1. Due to other projects that require my attention over the next few weeks, https://github.com/spicywebau/craft-neo/issues/100 has been pushed back to 5.1. I'm hoping I can have a look at it in April.

**Comment by ttempleton** [comment]
We still need to keep the concept of block types, because of the settings block types have that entry types don't have. I am planning (for the Neo 5.1 release) to add the option to associate a block type with an entry type, so that some block type settings, including the field layout, can be taken from the entry type.
