### ISSUE TITLE
Child blocks mixed up when reverting content from revision

### ISSUE THREAD

**Issue by gateszies** [spicywebau/craft-neo#816]
### Bug Description

When reverting to a previous version of an entry, Neo block children are being de-coupled from their parent thus breaking the block. This has happened both after applying a new draft, and when reverting the current version to a previous version. 

**Screenshare**
https://github.com/spicywebau/craft-neo/assets/66807975/3deccba9-2df9-4b5f-9f53-249482b4e035

### Steps to reproduce

1. Create a draft and apply to current entry (or start from the current version)
2. Revert to previous version of entry (you can see the tab with affected neo blocks shows up with no content)
3. Once applied, children are de-coupled from their parent block and have to be manually moved back in

### Neo version

3.9.5

### Craft CMS version

4.5.6.1

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by ttempleton** [comment]
I'm unable to reproduce this, but it looks similar to #805 which was fixed a while ago, and the revision being reverted to is a few months old, so I'm going to assume that revision was affected by that bug and that this issue is a duplicate. If you're not disabling Craft's `runQueueAutomatically` setting, or if this is still happening with a revision created much more recently (e.g. if you just edit that entry a few more times and revert to one of those revisions), then let me know and I'll reopen this issue.
