### ISSUE TITLE
When a neo field include matrix field, how use feedme to import data?

### ISSUE THREAD

**Issue by dande-sun** [spicywebau/craft-neo#829]
### What question would you like to ask?

When a neo field include matrix field, how use feedme to import data?

**Comment by dande-sun** [comment]
How do I import data into a child block using feedme?

**Comment by ttempleton** [comment]
Based on https://github.com/craftcms/feed-me/discussions/889 unfortunately it seems like Feed Me doesn't support importing data into nested block element fields yet. Hopefully something that's added in the Craft 5 version, since Craft 5 will allow Matrix fields within Matrix fields.

Importing into child/descendant blocks by setting block levels is covered in our [documentation](https://github.com/spicywebau/craft-neo/blob/4.0.2/docs/feed-me.md).
