### ISSUE TITLE
SQLSTATE[HY000]: General error: 1712 Index neoblocks is corrupted The SQL being executed was: <query>

### ISSUE THREAD

**Issue by Yanick64** [spicywebau/craft-neo#832]
### What question would you like to ask?

We are experiencing some problems with our CraftCMS installation in combination with the plugin Neo (https://plugins.craftcms.com/neo?craft4). When an editor tries to save a content item it goes wrong, then the content editor cannot open this item.

Within the Queue manager in CraftCMS, we therefore get the following error message back: "SQLSTATE[HY000]: General error: 1712 Index neoblocks is corrupted The SQL being executed was: <query>". Witihin the queue manager the "Pruning extra revisions" are failing aswell. To open the item next, we need to repair the database. 

I had found the following GitHub thread about perhaps this problem: https://github.com/craftcms/cms/issues/12456.

Do you guys have any experience with this on how to solve this problem? 

CraftCMS Version: 4.5.6.1
Neo Version: 3.9.4

Would like to hear from you.

**Comment by ttempleton** [comment]
I haven't seen this before, and I'm not sure what would've caused it, but it's unlikely to have been caused by Neo, since the other related Craft issue https://github.com/craftcms/cms/issues/13021 has examples of this happening with `matrixblocks` and `elements_sites`. Unfortunately the only thing I can really recommend is to look through that issue and https://github.com/craftcms/cms/issues/12456 for any suggestions for fixes that might work for you.
