### ISSUE TITLE
Creating Migrations for a plugin injecting fields into craft

### ISSUE THREAD

**Issue by FlipLucky** [spicywebau/craft-neo#833]
Hello!

I hope you can offer some advice/guidance with the following situation: 
I am currently building a plugin for a custom pagebuilder. 

Through plugin migrations, fields get created in the craft installation. 
- create craft primitive fields
- create neo fields
  - create neo blocks, and apply those fields to these blocks. 

The flow is, which each addon, a new migration is created to add fields, neo fields and blocks. 
I am running into several questions/issues

example neofield structure: 
- block a -> toplevel, can have child x  
- block b -> toplevel, can have child y
- section header Subblocks
- block x 
- block y

Issue 1: 
When running all the migrations, we need to define sortOrder to assign a block to a group. 
migration 1: add a
migration 2: add b

migration 2 fails, since the sortOrder is invalid

when running these separately, this is no issue. It seems like the migrations, although run in sequence, create a race condition, where both migration 1 and 2 get the same " free " slot in the sortOrder. 

Issue 2: 
When downing the migrations, if they are not run separate, but in one fell swoop, missing fields arise, leaving either ghost fields without a location, or failed down migrations. 

question 1: 
to add block x or y, i need to loop through all the available groups from the neo field, and filter out the group based on handle. This seems clunky. 
Is there a way to directly get a group by handle, instead of looping through all the groups of a neo field? ( hopefully, there is, and I had to little knowledge to find it ) 

I hope these questions are clear, and my apologies if I let out some crucial information. The whole process isn't constant, the results vary even though the code stays the same. 

The recap above is me trying to capture the overall flow of breakdowns. 

Is there a way I can solve this from the Neo side of things, or do I need to address craft to help me with these issues?

Thank you in advance!

**Comment by ttempleton** [comment]
There's no method inbuilt in Neo to get a block type group by its name - for now, you would have to do what you're doing now, although it would be worth adding something like that to Neo in the future.

Regarding the other issues - since it seems like they generally work fine when run separately, I'm wondering if, when running them in sequence, the second migration for some reason is working with cached data instead of the current state of the database. I'm not sure if that's what's happening, though, and I'm not sure if Neo itself would cause that. For testing purposes, I'd suggest having your migration create an entry section instead of a Neo field, and entry types instead of block types, and seeing if the same thing happens when trying to add fields to those.

**Comment by ttempleton** [comment]
Closing this for now, but please let me know if you have any follow-up questions.
