### ISSUE TITLE
Child blocks get jumbled when moving around blocks with autosaveDrafts = false

### ISSUE THREAD

**Issue by ajoliveau** [spicywebau/craft-neo#941]
### Bug Description

On Craft 4.X, when I set autosaveDrafts to false, if I move around childs with child blocks, they take all the blocks of the content just below, so I'm not able to save the new order.

### Steps to reproduce

Here is a minimal repo with only Craft 4, Neo (up-to-date) and a single entry type with a single field.

- Clone this repo : https://github.com/ajoliveau/craft-neo-bug
- Do a `ddev install` or whatever you use for you dev env
- Import the dump_craft-neo-bug.sql.gz db
- Login to the admin (admin / `neobug`) and go to /admin/entries/page/2-test-page
- Move the second field up, and press Ctrl + S
- You should see this error 
![image](https://github.com/user-attachments/assets/53600b48-2cd1-4486-94f4-be0c5b9b7f8a)
 

### Expected behaviour

I'm able to move fields around even if I don't have autosaveDrafts to true

### Neo version

4.2.12

### Craft CMS version

4.12.1

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by TheFunkyMonk** [comment]
I had a [similar issue](https://github.com/spicywebau/craft-neo/issues/937) (which just came up again) and running garbage collection with `php craft gc/run` fixed it; hopefully, that helps. Definitely something strange going on with garbage collection related to Neo.

**Comment by ttempleton** [comment]
Unfortunately this bug involves [part of the memoised block query code](https://github.com/spicywebau/craft-neo/blob/5.x/src/elements/db/BlockQuery.php#L1018-L1021) returning incorrect descendant blocks because the blocks have some old block structure data. I've had a thought about whether it would be safe to overwrite the `rgt` value with `sortOrder` while validating Neo field data, but haven't had a chance to test that yet.

**Comment by ttempleton** [comment]
Fixed now in 4.2.16, and also in the 5.x branch (hoping to resolve #929 before the next 5.x release).
